"""add_data_source_credentials_table

Revision ID: 003
Revises: 002_add_datasource_status_column
Create Date: 2025-11-12 13:10:16.456967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, Sequence[str], None] = "002_add_datasource_status_column"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_source_credential",
        sa.Column(
            "credential_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("data_source_id", sa.Uuid(), nullable=True),
        sa.Column(
            "credential_type",
            sa.Enum(
                "CLIENT_ID",
                "CLIENT_SECRET",
                "USERNAME",
                "PASSWORD",
                name="credentialtype",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"], ["data_source.data_source_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("credential_id"),
    )
    op.create_index(
        "unique_data_source_credential_type",
        "data_source_credential",
        ["data_source_id", "credential_type"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_data_source_credential_type", table_name="data_source_credential"
    )
    op.drop_table("data_source_credential")
    # ### end Alembic commands ###
