"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import builtins
import sys
from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .auth_callbackop import AuthCallbackRequest, AuthCallbackRequestTypedDict
    from .authdisconnectresponse import (
        AuthDisconnectResponse,
        AuthDisconnectResponseTypedDict,
    )
    from .authstartresponse import AuthStartResponse, AuthStartResponseTypedDict
    from .authuserinforesponse import (
        AuthUserInfoResponse,
        AuthUserInfoResponseTypedDict,
    )
    from .body_create_run_by_policy_version import (
        BodyCreateRunByPolicyVersion,
        BodyCreateRunByPolicyVersionTypedDict,
    )
    from .body_create_run_group import BodyCreateRunGroup, BodyCreateRunGroupTypedDict
    from .body_run_duration_stats_by_policy import (
        BodyRunDurationStatsByPolicy,
        BodyRunDurationStatsByPolicyTypedDict,
    )
    from .body_run_duration_stats_by_policy_status import (
        BodyRunDurationStatsByPolicyStatus,
        BodyRunDurationStatsByPolicyStatusTypedDict,
    )
    from .body_run_version_sync import BodyRunVersionSync, BodyRunVersionSyncTypedDict
    from .body_run_workflow import BodyRunWorkflow, BodyRunWorkflowTypedDict
    from .body_runs_by_policy import BodyRunsByPolicy, BodyRunsByPolicyTypedDict
    from .body_runs_outcomes_by_policy import (
        BodyRunsOutcomesByPolicy,
        BodyRunsOutcomesByPolicyTypedDict,
    )
    from .body_update_run import BodyUpdateRun, BodyUpdateRunTypedDict
    from .cachingoptions import (
        TTL,
        CachingOptions,
        CachingOptionsTypedDict,
        TTLTypedDict,
    )
    from .cachingttl import CachingTTL, CachingTTLTypedDict
    from .component import Component, ComponentTypedDict
    from .componentbase import ComponentBase, ComponentBaseTypedDict
    from .componentupdate import ComponentUpdate, ComponentUpdateTypedDict
    from .configurationvariables import (
        ConfigurationVariables,
        ConfigurationVariablesTypedDict,
        ConfigurationVariablesValue,
        ConfigurationVariablesValueTypedDict,
    )
    from .configurationvariablesbase import (
        ConfigurationVariablesBase,
        ConfigurationVariablesBaseTypedDict,
        ConfigurationVariablesBaseValue,
        ConfigurationVariablesBaseValueTypedDict,
    )
    from .create_componentop import (
        CreateComponentRequest,
        CreateComponentRequestTypedDict,
    )
    from .create_run_by_policy_versionop import (
        CreateRunByPolicyVersionRequest,
        CreateRunByPolicyVersionRequestTypedDict,
    )
    from .create_run_groupop import (
        CreateRunGroupRequest,
        CreateRunGroupRequestTypedDict,
    )
    from .dagsterlogdetails import DagsterLogDetails, DagsterLogDetailsTypedDict
    from .databrokerrequest import DataBrokerRequest, DataBrokerRequestTypedDict
    from .databrokerresponse import (
        DataBrokerResponse,
        DataBrokerResponseError,
        DataBrokerResponseErrorTypedDict,
        DataBrokerResponseTypedDict,
    )
    from .dataobject import DataObject, DataObjectTypedDict
    from .dataobjectmetadata import DataObjectMetadata, DataObjectMetadataTypedDict
    from .dataobjectorigin import DataObjectOrigin
    from .datasource import (
        DataSource,
        DataSourceSource,
        DataSourceSourceTypedDict,
        DataSourceTypedDict,
    )
    from .datasourceenvvar import (
        DataSourceEnvVar,
        DataSourceEnvVarTypedDict,
        DataSourceEnvVarValue,
        DataSourceEnvVarValueTypedDict,
    )
    from .datasourceenvvarbase import (
        DataSourceEnvVarBase,
        DataSourceEnvVarBaseTypedDict,
        DataSourceEnvVarBaseValue,
        DataSourceEnvVarBaseValueTypedDict,
    )
    from .datasourcereference import DataSourceReference, DataSourceReferenceTypedDict
    from .datasourcespec import (
        DataSourceSpec,
        DataSourceSpecSource,
        DataSourceSpecSourceTypedDict,
        DataSourceSpecTypedDict,
    )
    from .delete_componentop import (
        DeleteComponentRequest,
        DeleteComponentRequestTypedDict,
    )
    from .delete_data_sourceop import (
        DeleteDataSourceRequest,
        DeleteDataSourceRequestTypedDict,
    )
    from .delete_policy_versionop import (
        DeletePolicyVersionRequest,
        DeletePolicyVersionRequestTypedDict,
    )
    from .delete_policyop import DeletePolicyRequest, DeletePolicyRequestTypedDict
    from .dependencydict import DependencyDict, DependencyDictTypedDict
    from .disconnectop import DisconnectRequest, DisconnectRequestTypedDict
    from .envvarconfig import EnvVarConfig, EnvVarConfigTypedDict
    from .get_cache_statisticsop import (
        GetCacheStatisticsRequest,
        GetCacheStatisticsRequestTypedDict,
    )
    from .get_componentop import GetComponentRequest, GetComponentRequestTypedDict
    from .get_data_objectop import GetDataObjectRequest, GetDataObjectRequestTypedDict
    from .get_data_source_env_variablesop import (
        GetDataSourceEnvVariablesRequest,
        GetDataSourceEnvVariablesRequestTypedDict,
    )
    from .get_data_source_metricsop import (
        GetDataSourceMetricsRequest,
        GetDataSourceMetricsRequestTypedDict,
    )
    from .get_data_source_usageop import (
        GetDataSourceUsageRequest,
        GetDataSourceUsageRequestTypedDict,
    )
    from .get_data_sourceop import GetDataSourceRequest, GetDataSourceRequestTypedDict
    from .get_policy_versionop import (
        GetPolicyVersionRequest,
        GetPolicyVersionRequestTypedDict,
    )
    from .get_policyop import GetPolicyRequest, GetPolicyRequestTypedDict
    from .get_run_dataop import GetRunDataRequest, GetRunDataRequestTypedDict
    from .get_run_logsop import GetRunLogsRequest, GetRunLogsRequestTypedDict
    from .get_runop import GetRunRequest, GetRunRequestTypedDict
    from .get_user_infoop import GetUserInfoRequest, GetUserInfoRequestTypedDict
    from .httpsource import (
        Body1,
        Body1TypedDict,
        Body2,
        Body2TypedDict,
        Body3,
        Body3TypedDict,
        Body4,
        Body4TypedDict,
        Body5,
        Body5TypedDict,
        Body6,
        Body6TypedDict,
        Headers1,
        Headers1TypedDict,
        Headers2,
        Headers2TypedDict,
        Headers3,
        Headers3TypedDict,
        Headers4,
        Headers4TypedDict,
        Headers5,
        Headers5TypedDict,
        Headers6,
        Headers6TypedDict,
        HTTPSource,
        HTTPSourceTypedDict,
        Method,
        Params1,
        Params1TypedDict,
        Params2,
        Params2TypedDict,
        Params3,
        Params3TypedDict,
        Params4,
        Params4TypedDict,
        Params5,
        Params5TypedDict,
        Params6,
        Params6TypedDict,
        ResponseType,
    )
    from .list_componentsop import ListComponentsRequest, ListComponentsRequestTypedDict
    from .list_config_variablesop import (
        ListConfigVariablesRequest,
        ListConfigVariablesRequestTypedDict,
    )
    from .list_data_objectsop import (
        ListDataObjectsRequest,
        ListDataObjectsRequestTypedDict,
    )
    from .list_data_sources_by_policy_versionop import (
        ListDataSourcesByPolicyVersionRequest,
        ListDataSourcesByPolicyVersionRequestTypedDict,
    )
    from .list_data_sourcesop import (
        ListDataSourcesRequest,
        ListDataSourcesRequestTypedDict,
    )
    from .list_policiesop import ListPoliciesRequest, ListPoliciesRequestTypedDict
    from .list_policy_versions_by_policyop import (
        ListPolicyVersionsByPolicyRequest,
        ListPolicyVersionsByPolicyRequestTypedDict,
    )
    from .list_policy_versionsop import (
        ListPolicyVersionsRequest,
        ListPolicyVersionsRequestTypedDict,
    )
    from .list_runs_by_policy_versionop import (
        ListRunsByPolicyVersionRequest,
        ListRunsByPolicyVersionRequestTypedDict,
    )
    from .list_runs_by_policyop import (
        ListRunsByPolicyRequest,
        ListRunsByPolicyRequestTypedDict,
    )
    from .localfilesource import LocalFileSource, LocalFileSourceTypedDict
    from .logentry import Event, EventTypedDict, LogEntry, LogEntryTypedDict
    from .nodedefinitiondict import NodeDefinitionDict, NodeDefinitionDictTypedDict
    from .policy import Policy, PolicyTypedDict
    from .policyallocationstrategy import (
        PolicyAllocationStrategy,
        PolicyAllocationStrategyTypedDict,
    )
    from .policybase import PolicyBase, PolicyBaseTypedDict
    from .policycreate import PolicyCreate, PolicyCreateTypedDict
    from .policydefinitiondict import (
        PolicyDefinitionDict,
        PolicyDefinitionDictTypedDict,
    )
    from .policyrunpartition import PolicyRunPartition, PolicyRunPartitionTypedDict
    from .policyversion import PolicyVersion, PolicyVersionTypedDict
    from .policyversionbase import PolicyVersionBase, PolicyVersionBaseTypedDict
    from .policyversionupdate import PolicyVersionUpdate, PolicyVersionUpdateTypedDict
    from .publish_metadataop import (
        PublishMetadataRequest,
        PublishMetadataRequestTypedDict,
    )
    from .registeredfilesource import (
        RegisteredFileSource,
        RegisteredFileSourceTypedDict,
    )
    from .retrypolicy import RetryPolicy, RetryPolicyTypedDict
    from .run import Run, RunTypedDict
    from .run_duration_stats_by_policy_statusop import (
        RunDurationStatsByPolicyStatusRequest,
        RunDurationStatsByPolicyStatusRequestTypedDict,
    )
    from .run_duration_stats_by_policyop import (
        RunDurationStatsByPolicyRequest,
        RunDurationStatsByPolicyRequestTypedDict,
    )
    from .run_version_syncop import (
        RunVersionSyncRequest,
        RunVersionSyncRequestTypedDict,
    )
    from .run_workflowop import RunWorkflowRequest, RunWorkflowRequestTypedDict
    from .runcreated import RunCreated, RunCreatedTypedDict
    from .rundata import RunData, RunDataTypedDict
    from .rungroupresult import RunGroupResult, RunGroupResultTypedDict
    from .rungroupruns import RunGroupRuns, RunGroupRunsTypedDict
    from .runlogs import RunLogs, RunLogsTypedDict
    from .runresult import RunResult, RunResultTypedDict
    from .runs_by_policyop import RunsByPolicyRequest, RunsByPolicyRequestTypedDict
    from .runs_outcomes_by_policyop import (
        RunsOutcomesByPolicyRequest,
        RunsOutcomesByPolicyRequestTypedDict,
    )
    from .runstatus import RunStatus
    from .runtimeparam import RunTimeParam, RunTimeParamTypedDict, ValueType
    from .set_config_variablesop import (
        SetConfigVariablesRequest,
        SetConfigVariablesRequestTypedDict,
    )
    from .set_data_source_env_variablesop import (
        SetDataSourceEnvVariablesRequest,
        SetDataSourceEnvVariablesRequestTypedDict,
    )
    from .start_authop import StartAuthRequest, StartAuthRequestTypedDict
    from .stepdetails import Output, OutputTypedDict, StepDetails, StepDetailsTypedDict
    from .stepmetadatabase import (
        StepMetadataBase,
        StepMetadataBaseError,
        StepMetadataBaseErrorTypedDict,
        StepMetadataBaseTypedDict,
    )
    from .uimetadata import UIMetadata, UIMetadataTypedDict
    from .uinodeposition import UINodePosition, UINodePositionTypedDict
    from .update_componentop import (
        UpdateComponentRequest,
        UpdateComponentRequestTypedDict,
    )
    from .update_policy_versionop import (
        UpdatePolicyVersionRequest,
        UpdatePolicyVersionRequestTypedDict,
    )
    from .update_policyop import UpdatePolicyRequest, UpdatePolicyRequestTypedDict
    from .update_runop import UpdateRunRequest, UpdateRunRequestTypedDict
    from .userlogdetails import UserLogDetails, UserLogDetailsTypedDict
    from .validationerror import (
        Loc,
        LocTypedDict,
        ValidationError,
        ValidationErrorTypedDict,
    )
    from .workflow import Workflow, WorkflowTypedDict
    from .workflowbase import WorkflowBase, WorkflowBaseTypedDict
    from .workflowstatus import WorkflowStatus

__all__ = [
    "AuthCallbackRequest",
    "AuthCallbackRequestTypedDict",
    "AuthDisconnectResponse",
    "AuthDisconnectResponseTypedDict",
    "AuthStartResponse",
    "AuthStartResponseTypedDict",
    "AuthUserInfoResponse",
    "AuthUserInfoResponseTypedDict",
    "Body1",
    "Body1TypedDict",
    "Body2",
    "Body2TypedDict",
    "Body3",
    "Body3TypedDict",
    "Body4",
    "Body4TypedDict",
    "Body5",
    "Body5TypedDict",
    "Body6",
    "Body6TypedDict",
    "BodyCreateRunByPolicyVersion",
    "BodyCreateRunByPolicyVersionTypedDict",
    "BodyCreateRunGroup",
    "BodyCreateRunGroupTypedDict",
    "BodyRunDurationStatsByPolicy",
    "BodyRunDurationStatsByPolicyStatus",
    "BodyRunDurationStatsByPolicyStatusTypedDict",
    "BodyRunDurationStatsByPolicyTypedDict",
    "BodyRunVersionSync",
    "BodyRunVersionSyncTypedDict",
    "BodyRunWorkflow",
    "BodyRunWorkflowTypedDict",
    "BodyRunsByPolicy",
    "BodyRunsByPolicyTypedDict",
    "BodyRunsOutcomesByPolicy",
    "BodyRunsOutcomesByPolicyTypedDict",
    "BodyUpdateRun",
    "BodyUpdateRunTypedDict",
    "CachingOptions",
    "CachingOptionsTypedDict",
    "CachingTTL",
    "CachingTTLTypedDict",
    "Component",
    "ComponentBase",
    "ComponentBaseTypedDict",
    "ComponentTypedDict",
    "ComponentUpdate",
    "ComponentUpdateTypedDict",
    "ConfigurationVariables",
    "ConfigurationVariablesBase",
    "ConfigurationVariablesBaseTypedDict",
    "ConfigurationVariablesBaseValue",
    "ConfigurationVariablesBaseValueTypedDict",
    "ConfigurationVariablesTypedDict",
    "ConfigurationVariablesValue",
    "ConfigurationVariablesValueTypedDict",
    "CreateComponentRequest",
    "CreateComponentRequestTypedDict",
    "CreateRunByPolicyVersionRequest",
    "CreateRunByPolicyVersionRequestTypedDict",
    "CreateRunGroupRequest",
    "CreateRunGroupRequestTypedDict",
    "DagsterLogDetails",
    "DagsterLogDetailsTypedDict",
    "DataBrokerRequest",
    "DataBrokerRequestTypedDict",
    "DataBrokerResponse",
    "DataBrokerResponseError",
    "DataBrokerResponseErrorTypedDict",
    "DataBrokerResponseTypedDict",
    "DataObject",
    "DataObjectMetadata",
    "DataObjectMetadataTypedDict",
    "DataObjectOrigin",
    "DataObjectTypedDict",
    "DataSource",
    "DataSourceEnvVar",
    "DataSourceEnvVarBase",
    "DataSourceEnvVarBaseTypedDict",
    "DataSourceEnvVarBaseValue",
    "DataSourceEnvVarBaseValueTypedDict",
    "DataSourceEnvVarTypedDict",
    "DataSourceEnvVarValue",
    "DataSourceEnvVarValueTypedDict",
    "DataSourceReference",
    "DataSourceReferenceTypedDict",
    "DataSourceSource",
    "DataSourceSourceTypedDict",
    "DataSourceSpec",
    "DataSourceSpecSource",
    "DataSourceSpecSourceTypedDict",
    "DataSourceSpecTypedDict",
    "DataSourceTypedDict",
    "DeleteComponentRequest",
    "DeleteComponentRequestTypedDict",
    "DeleteDataSourceRequest",
    "DeleteDataSourceRequestTypedDict",
    "DeletePolicyRequest",
    "DeletePolicyRequestTypedDict",
    "DeletePolicyVersionRequest",
    "DeletePolicyVersionRequestTypedDict",
    "DependencyDict",
    "DependencyDictTypedDict",
    "DisconnectRequest",
    "DisconnectRequestTypedDict",
    "EnvVarConfig",
    "EnvVarConfigTypedDict",
    "Event",
    "EventTypedDict",
    "GetCacheStatisticsRequest",
    "GetCacheStatisticsRequestTypedDict",
    "GetComponentRequest",
    "GetComponentRequestTypedDict",
    "GetDataObjectRequest",
    "GetDataObjectRequestTypedDict",
    "GetDataSourceEnvVariablesRequest",
    "GetDataSourceEnvVariablesRequestTypedDict",
    "GetDataSourceMetricsRequest",
    "GetDataSourceMetricsRequestTypedDict",
    "GetDataSourceRequest",
    "GetDataSourceRequestTypedDict",
    "GetDataSourceUsageRequest",
    "GetDataSourceUsageRequestTypedDict",
    "GetPolicyRequest",
    "GetPolicyRequestTypedDict",
    "GetPolicyVersionRequest",
    "GetPolicyVersionRequestTypedDict",
    "GetRunDataRequest",
    "GetRunDataRequestTypedDict",
    "GetRunLogsRequest",
    "GetRunLogsRequestTypedDict",
    "GetRunRequest",
    "GetRunRequestTypedDict",
    "GetUserInfoRequest",
    "GetUserInfoRequestTypedDict",
    "HTTPSource",
    "HTTPSourceTypedDict",
    "Headers1",
    "Headers1TypedDict",
    "Headers2",
    "Headers2TypedDict",
    "Headers3",
    "Headers3TypedDict",
    "Headers4",
    "Headers4TypedDict",
    "Headers5",
    "Headers5TypedDict",
    "Headers6",
    "Headers6TypedDict",
    "ListComponentsRequest",
    "ListComponentsRequestTypedDict",
    "ListConfigVariablesRequest",
    "ListConfigVariablesRequestTypedDict",
    "ListDataObjectsRequest",
    "ListDataObjectsRequestTypedDict",
    "ListDataSourcesByPolicyVersionRequest",
    "ListDataSourcesByPolicyVersionRequestTypedDict",
    "ListDataSourcesRequest",
    "ListDataSourcesRequestTypedDict",
    "ListPoliciesRequest",
    "ListPoliciesRequestTypedDict",
    "ListPolicyVersionsByPolicyRequest",
    "ListPolicyVersionsByPolicyRequestTypedDict",
    "ListPolicyVersionsRequest",
    "ListPolicyVersionsRequestTypedDict",
    "ListRunsByPolicyRequest",
    "ListRunsByPolicyRequestTypedDict",
    "ListRunsByPolicyVersionRequest",
    "ListRunsByPolicyVersionRequestTypedDict",
    "Loc",
    "LocTypedDict",
    "LocalFileSource",
    "LocalFileSourceTypedDict",
    "LogEntry",
    "LogEntryTypedDict",
    "Method",
    "NodeDefinitionDict",
    "NodeDefinitionDictTypedDict",
    "Output",
    "OutputTypedDict",
    "Params1",
    "Params1TypedDict",
    "Params2",
    "Params2TypedDict",
    "Params3",
    "Params3TypedDict",
    "Params4",
    "Params4TypedDict",
    "Params5",
    "Params5TypedDict",
    "Params6",
    "Params6TypedDict",
    "Policy",
    "PolicyAllocationStrategy",
    "PolicyAllocationStrategyTypedDict",
    "PolicyBase",
    "PolicyBaseTypedDict",
    "PolicyCreate",
    "PolicyCreateTypedDict",
    "PolicyDefinitionDict",
    "PolicyDefinitionDictTypedDict",
    "PolicyRunPartition",
    "PolicyRunPartitionTypedDict",
    "PolicyTypedDict",
    "PolicyVersion",
    "PolicyVersionBase",
    "PolicyVersionBaseTypedDict",
    "PolicyVersionTypedDict",
    "PolicyVersionUpdate",
    "PolicyVersionUpdateTypedDict",
    "PublishMetadataRequest",
    "PublishMetadataRequestTypedDict",
    "RegisteredFileSource",
    "RegisteredFileSourceTypedDict",
    "ResponseType",
    "RetryPolicy",
    "RetryPolicyTypedDict",
    "Run",
    "RunCreated",
    "RunCreatedTypedDict",
    "RunData",
    "RunDataTypedDict",
    "RunDurationStatsByPolicyRequest",
    "RunDurationStatsByPolicyRequestTypedDict",
    "RunDurationStatsByPolicyStatusRequest",
    "RunDurationStatsByPolicyStatusRequestTypedDict",
    "RunGroupResult",
    "RunGroupResultTypedDict",
    "RunGroupRuns",
    "RunGroupRunsTypedDict",
    "RunLogs",
    "RunLogsTypedDict",
    "RunResult",
    "RunResultTypedDict",
    "RunStatus",
    "RunTimeParam",
    "RunTimeParamTypedDict",
    "RunTypedDict",
    "RunVersionSyncRequest",
    "RunVersionSyncRequestTypedDict",
    "RunWorkflowRequest",
    "RunWorkflowRequestTypedDict",
    "RunsByPolicyRequest",
    "RunsByPolicyRequestTypedDict",
    "RunsOutcomesByPolicyRequest",
    "RunsOutcomesByPolicyRequestTypedDict",
    "SetConfigVariablesRequest",
    "SetConfigVariablesRequestTypedDict",
    "SetDataSourceEnvVariablesRequest",
    "SetDataSourceEnvVariablesRequestTypedDict",
    "StartAuthRequest",
    "StartAuthRequestTypedDict",
    "StepDetails",
    "StepDetailsTypedDict",
    "StepMetadataBase",
    "StepMetadataBaseError",
    "StepMetadataBaseErrorTypedDict",
    "StepMetadataBaseTypedDict",
    "TTL",
    "TTLTypedDict",
    "UIMetadata",
    "UIMetadataTypedDict",
    "UINodePosition",
    "UINodePositionTypedDict",
    "UpdateComponentRequest",
    "UpdateComponentRequestTypedDict",
    "UpdatePolicyRequest",
    "UpdatePolicyRequestTypedDict",
    "UpdatePolicyVersionRequest",
    "UpdatePolicyVersionRequestTypedDict",
    "UpdateRunRequest",
    "UpdateRunRequestTypedDict",
    "UserLogDetails",
    "UserLogDetailsTypedDict",
    "ValidationError",
    "ValidationErrorTypedDict",
    "ValueType",
    "Workflow",
    "WorkflowBase",
    "WorkflowBaseTypedDict",
    "WorkflowStatus",
    "WorkflowTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AuthCallbackRequest": ".auth_callbackop",
    "AuthCallbackRequestTypedDict": ".auth_callbackop",
    "AuthDisconnectResponse": ".authdisconnectresponse",
    "AuthDisconnectResponseTypedDict": ".authdisconnectresponse",
    "AuthStartResponse": ".authstartresponse",
    "AuthStartResponseTypedDict": ".authstartresponse",
    "AuthUserInfoResponse": ".authuserinforesponse",
    "AuthUserInfoResponseTypedDict": ".authuserinforesponse",
    "BodyCreateRunByPolicyVersion": ".body_create_run_by_policy_version",
    "BodyCreateRunByPolicyVersionTypedDict": ".body_create_run_by_policy_version",
    "BodyCreateRunGroup": ".body_create_run_group",
    "BodyCreateRunGroupTypedDict": ".body_create_run_group",
    "BodyRunDurationStatsByPolicy": ".body_run_duration_stats_by_policy",
    "BodyRunDurationStatsByPolicyTypedDict": ".body_run_duration_stats_by_policy",
    "BodyRunDurationStatsByPolicyStatus": ".body_run_duration_stats_by_policy_status",
    "BodyRunDurationStatsByPolicyStatusTypedDict": ".body_run_duration_stats_by_policy_status",
    "BodyRunVersionSync": ".body_run_version_sync",
    "BodyRunVersionSyncTypedDict": ".body_run_version_sync",
    "BodyRunWorkflow": ".body_run_workflow",
    "BodyRunWorkflowTypedDict": ".body_run_workflow",
    "BodyRunsByPolicy": ".body_runs_by_policy",
    "BodyRunsByPolicyTypedDict": ".body_runs_by_policy",
    "BodyRunsOutcomesByPolicy": ".body_runs_outcomes_by_policy",
    "BodyRunsOutcomesByPolicyTypedDict": ".body_runs_outcomes_by_policy",
    "BodyUpdateRun": ".body_update_run",
    "BodyUpdateRunTypedDict": ".body_update_run",
    "CachingOptions": ".cachingoptions",
    "CachingOptionsTypedDict": ".cachingoptions",
    "TTL": ".cachingoptions",
    "TTLTypedDict": ".cachingoptions",
    "CachingTTL": ".cachingttl",
    "CachingTTLTypedDict": ".cachingttl",
    "Component": ".component",
    "ComponentTypedDict": ".component",
    "ComponentBase": ".componentbase",
    "ComponentBaseTypedDict": ".componentbase",
    "ComponentUpdate": ".componentupdate",
    "ComponentUpdateTypedDict": ".componentupdate",
    "ConfigurationVariables": ".configurationvariables",
    "ConfigurationVariablesTypedDict": ".configurationvariables",
    "ConfigurationVariablesValue": ".configurationvariables",
    "ConfigurationVariablesValueTypedDict": ".configurationvariables",
    "ConfigurationVariablesBase": ".configurationvariablesbase",
    "ConfigurationVariablesBaseTypedDict": ".configurationvariablesbase",
    "ConfigurationVariablesBaseValue": ".configurationvariablesbase",
    "ConfigurationVariablesBaseValueTypedDict": ".configurationvariablesbase",
    "CreateComponentRequest": ".create_componentop",
    "CreateComponentRequestTypedDict": ".create_componentop",
    "CreateRunByPolicyVersionRequest": ".create_run_by_policy_versionop",
    "CreateRunByPolicyVersionRequestTypedDict": ".create_run_by_policy_versionop",
    "CreateRunGroupRequest": ".create_run_groupop",
    "CreateRunGroupRequestTypedDict": ".create_run_groupop",
    "DagsterLogDetails": ".dagsterlogdetails",
    "DagsterLogDetailsTypedDict": ".dagsterlogdetails",
    "DataBrokerRequest": ".databrokerrequest",
    "DataBrokerRequestTypedDict": ".databrokerrequest",
    "DataBrokerResponse": ".databrokerresponse",
    "DataBrokerResponseError": ".databrokerresponse",
    "DataBrokerResponseErrorTypedDict": ".databrokerresponse",
    "DataBrokerResponseTypedDict": ".databrokerresponse",
    "DataObject": ".dataobject",
    "DataObjectTypedDict": ".dataobject",
    "DataObjectMetadata": ".dataobjectmetadata",
    "DataObjectMetadataTypedDict": ".dataobjectmetadata",
    "DataObjectOrigin": ".dataobjectorigin",
    "DataSource": ".datasource",
    "DataSourceSource": ".datasource",
    "DataSourceSourceTypedDict": ".datasource",
    "DataSourceTypedDict": ".datasource",
    "DataSourceEnvVar": ".datasourceenvvar",
    "DataSourceEnvVarTypedDict": ".datasourceenvvar",
    "DataSourceEnvVarValue": ".datasourceenvvar",
    "DataSourceEnvVarValueTypedDict": ".datasourceenvvar",
    "DataSourceEnvVarBase": ".datasourceenvvarbase",
    "DataSourceEnvVarBaseTypedDict": ".datasourceenvvarbase",
    "DataSourceEnvVarBaseValue": ".datasourceenvvarbase",
    "DataSourceEnvVarBaseValueTypedDict": ".datasourceenvvarbase",
    "DataSourceReference": ".datasourcereference",
    "DataSourceReferenceTypedDict": ".datasourcereference",
    "DataSourceSpec": ".datasourcespec",
    "DataSourceSpecSource": ".datasourcespec",
    "DataSourceSpecSourceTypedDict": ".datasourcespec",
    "DataSourceSpecTypedDict": ".datasourcespec",
    "DeleteComponentRequest": ".delete_componentop",
    "DeleteComponentRequestTypedDict": ".delete_componentop",
    "DeleteDataSourceRequest": ".delete_data_sourceop",
    "DeleteDataSourceRequestTypedDict": ".delete_data_sourceop",
    "DeletePolicyVersionRequest": ".delete_policy_versionop",
    "DeletePolicyVersionRequestTypedDict": ".delete_policy_versionop",
    "DeletePolicyRequest": ".delete_policyop",
    "DeletePolicyRequestTypedDict": ".delete_policyop",
    "DependencyDict": ".dependencydict",
    "DependencyDictTypedDict": ".dependencydict",
    "DisconnectRequest": ".disconnectop",
    "DisconnectRequestTypedDict": ".disconnectop",
    "EnvVarConfig": ".envvarconfig",
    "EnvVarConfigTypedDict": ".envvarconfig",
    "GetCacheStatisticsRequest": ".get_cache_statisticsop",
    "GetCacheStatisticsRequestTypedDict": ".get_cache_statisticsop",
    "GetComponentRequest": ".get_componentop",
    "GetComponentRequestTypedDict": ".get_componentop",
    "GetDataObjectRequest": ".get_data_objectop",
    "GetDataObjectRequestTypedDict": ".get_data_objectop",
    "GetDataSourceEnvVariablesRequest": ".get_data_source_env_variablesop",
    "GetDataSourceEnvVariablesRequestTypedDict": ".get_data_source_env_variablesop",
    "GetDataSourceMetricsRequest": ".get_data_source_metricsop",
    "GetDataSourceMetricsRequestTypedDict": ".get_data_source_metricsop",
    "GetDataSourceUsageRequest": ".get_data_source_usageop",
    "GetDataSourceUsageRequestTypedDict": ".get_data_source_usageop",
    "GetDataSourceRequest": ".get_data_sourceop",
    "GetDataSourceRequestTypedDict": ".get_data_sourceop",
    "GetPolicyVersionRequest": ".get_policy_versionop",
    "GetPolicyVersionRequestTypedDict": ".get_policy_versionop",
    "GetPolicyRequest": ".get_policyop",
    "GetPolicyRequestTypedDict": ".get_policyop",
    "GetRunDataRequest": ".get_run_dataop",
    "GetRunDataRequestTypedDict": ".get_run_dataop",
    "GetRunLogsRequest": ".get_run_logsop",
    "GetRunLogsRequestTypedDict": ".get_run_logsop",
    "GetRunRequest": ".get_runop",
    "GetRunRequestTypedDict": ".get_runop",
    "GetUserInfoRequest": ".get_user_infoop",
    "GetUserInfoRequestTypedDict": ".get_user_infoop",
    "Body1": ".httpsource",
    "Body1TypedDict": ".httpsource",
    "Body2": ".httpsource",
    "Body2TypedDict": ".httpsource",
    "Body3": ".httpsource",
    "Body3TypedDict": ".httpsource",
    "Body4": ".httpsource",
    "Body4TypedDict": ".httpsource",
    "Body5": ".httpsource",
    "Body5TypedDict": ".httpsource",
    "Body6": ".httpsource",
    "Body6TypedDict": ".httpsource",
    "HTTPSource": ".httpsource",
    "HTTPSourceTypedDict": ".httpsource",
    "Headers1": ".httpsource",
    "Headers1TypedDict": ".httpsource",
    "Headers2": ".httpsource",
    "Headers2TypedDict": ".httpsource",
    "Headers3": ".httpsource",
    "Headers3TypedDict": ".httpsource",
    "Headers4": ".httpsource",
    "Headers4TypedDict": ".httpsource",
    "Headers5": ".httpsource",
    "Headers5TypedDict": ".httpsource",
    "Headers6": ".httpsource",
    "Headers6TypedDict": ".httpsource",
    "Method": ".httpsource",
    "Params1": ".httpsource",
    "Params1TypedDict": ".httpsource",
    "Params2": ".httpsource",
    "Params2TypedDict": ".httpsource",
    "Params3": ".httpsource",
    "Params3TypedDict": ".httpsource",
    "Params4": ".httpsource",
    "Params4TypedDict": ".httpsource",
    "Params5": ".httpsource",
    "Params5TypedDict": ".httpsource",
    "Params6": ".httpsource",
    "Params6TypedDict": ".httpsource",
    "ResponseType": ".httpsource",
    "ListComponentsRequest": ".list_componentsop",
    "ListComponentsRequestTypedDict": ".list_componentsop",
    "ListConfigVariablesRequest": ".list_config_variablesop",
    "ListConfigVariablesRequestTypedDict": ".list_config_variablesop",
    "ListDataObjectsRequest": ".list_data_objectsop",
    "ListDataObjectsRequestTypedDict": ".list_data_objectsop",
    "ListDataSourcesByPolicyVersionRequest": ".list_data_sources_by_policy_versionop",
    "ListDataSourcesByPolicyVersionRequestTypedDict": ".list_data_sources_by_policy_versionop",
    "ListDataSourcesRequest": ".list_data_sourcesop",
    "ListDataSourcesRequestTypedDict": ".list_data_sourcesop",
    "ListPoliciesRequest": ".list_policiesop",
    "ListPoliciesRequestTypedDict": ".list_policiesop",
    "ListPolicyVersionsByPolicyRequest": ".list_policy_versions_by_policyop",
    "ListPolicyVersionsByPolicyRequestTypedDict": ".list_policy_versions_by_policyop",
    "ListPolicyVersionsRequest": ".list_policy_versionsop",
    "ListPolicyVersionsRequestTypedDict": ".list_policy_versionsop",
    "ListRunsByPolicyVersionRequest": ".list_runs_by_policy_versionop",
    "ListRunsByPolicyVersionRequestTypedDict": ".list_runs_by_policy_versionop",
    "ListRunsByPolicyRequest": ".list_runs_by_policyop",
    "ListRunsByPolicyRequestTypedDict": ".list_runs_by_policyop",
    "LocalFileSource": ".localfilesource",
    "LocalFileSourceTypedDict": ".localfilesource",
    "Event": ".logentry",
    "EventTypedDict": ".logentry",
    "LogEntry": ".logentry",
    "LogEntryTypedDict": ".logentry",
    "NodeDefinitionDict": ".nodedefinitiondict",
    "NodeDefinitionDictTypedDict": ".nodedefinitiondict",
    "Policy": ".policy",
    "PolicyTypedDict": ".policy",
    "PolicyAllocationStrategy": ".policyallocationstrategy",
    "PolicyAllocationStrategyTypedDict": ".policyallocationstrategy",
    "PolicyBase": ".policybase",
    "PolicyBaseTypedDict": ".policybase",
    "PolicyCreate": ".policycreate",
    "PolicyCreateTypedDict": ".policycreate",
    "PolicyDefinitionDict": ".policydefinitiondict",
    "PolicyDefinitionDictTypedDict": ".policydefinitiondict",
    "PolicyRunPartition": ".policyrunpartition",
    "PolicyRunPartitionTypedDict": ".policyrunpartition",
    "PolicyVersion": ".policyversion",
    "PolicyVersionTypedDict": ".policyversion",
    "PolicyVersionBase": ".policyversionbase",
    "PolicyVersionBaseTypedDict": ".policyversionbase",
    "PolicyVersionUpdate": ".policyversionupdate",
    "PolicyVersionUpdateTypedDict": ".policyversionupdate",
    "PublishMetadataRequest": ".publish_metadataop",
    "PublishMetadataRequestTypedDict": ".publish_metadataop",
    "RegisteredFileSource": ".registeredfilesource",
    "RegisteredFileSourceTypedDict": ".registeredfilesource",
    "RetryPolicy": ".retrypolicy",
    "RetryPolicyTypedDict": ".retrypolicy",
    "Run": ".run",
    "RunTypedDict": ".run",
    "RunDurationStatsByPolicyStatusRequest": ".run_duration_stats_by_policy_statusop",
    "RunDurationStatsByPolicyStatusRequestTypedDict": ".run_duration_stats_by_policy_statusop",
    "RunDurationStatsByPolicyRequest": ".run_duration_stats_by_policyop",
    "RunDurationStatsByPolicyRequestTypedDict": ".run_duration_stats_by_policyop",
    "RunVersionSyncRequest": ".run_version_syncop",
    "RunVersionSyncRequestTypedDict": ".run_version_syncop",
    "RunWorkflowRequest": ".run_workflowop",
    "RunWorkflowRequestTypedDict": ".run_workflowop",
    "RunCreated": ".runcreated",
    "RunCreatedTypedDict": ".runcreated",
    "RunData": ".rundata",
    "RunDataTypedDict": ".rundata",
    "RunGroupResult": ".rungroupresult",
    "RunGroupResultTypedDict": ".rungroupresult",
    "RunGroupRuns": ".rungroupruns",
    "RunGroupRunsTypedDict": ".rungroupruns",
    "RunLogs": ".runlogs",
    "RunLogsTypedDict": ".runlogs",
    "RunResult": ".runresult",
    "RunResultTypedDict": ".runresult",
    "RunsByPolicyRequest": ".runs_by_policyop",
    "RunsByPolicyRequestTypedDict": ".runs_by_policyop",
    "RunsOutcomesByPolicyRequest": ".runs_outcomes_by_policyop",
    "RunsOutcomesByPolicyRequestTypedDict": ".runs_outcomes_by_policyop",
    "RunStatus": ".runstatus",
    "RunTimeParam": ".runtimeparam",
    "RunTimeParamTypedDict": ".runtimeparam",
    "ValueType": ".runtimeparam",
    "SetConfigVariablesRequest": ".set_config_variablesop",
    "SetConfigVariablesRequestTypedDict": ".set_config_variablesop",
    "SetDataSourceEnvVariablesRequest": ".set_data_source_env_variablesop",
    "SetDataSourceEnvVariablesRequestTypedDict": ".set_data_source_env_variablesop",
    "StartAuthRequest": ".start_authop",
    "StartAuthRequestTypedDict": ".start_authop",
    "Output": ".stepdetails",
    "OutputTypedDict": ".stepdetails",
    "StepDetails": ".stepdetails",
    "StepDetailsTypedDict": ".stepdetails",
    "StepMetadataBase": ".stepmetadatabase",
    "StepMetadataBaseError": ".stepmetadatabase",
    "StepMetadataBaseErrorTypedDict": ".stepmetadatabase",
    "StepMetadataBaseTypedDict": ".stepmetadatabase",
    "UIMetadata": ".uimetadata",
    "UIMetadataTypedDict": ".uimetadata",
    "UINodePosition": ".uinodeposition",
    "UINodePositionTypedDict": ".uinodeposition",
    "UpdateComponentRequest": ".update_componentop",
    "UpdateComponentRequestTypedDict": ".update_componentop",
    "UpdatePolicyVersionRequest": ".update_policy_versionop",
    "UpdatePolicyVersionRequestTypedDict": ".update_policy_versionop",
    "UpdatePolicyRequest": ".update_policyop",
    "UpdatePolicyRequestTypedDict": ".update_policyop",
    "UpdateRunRequest": ".update_runop",
    "UpdateRunRequestTypedDict": ".update_runop",
    "UserLogDetails": ".userlogdetails",
    "UserLogDetailsTypedDict": ".userlogdetails",
    "Loc": ".validationerror",
    "LocTypedDict": ".validationerror",
    "ValidationError": ".validationerror",
    "ValidationErrorTypedDict": ".validationerror",
    "Workflow": ".workflow",
    "WorkflowTypedDict": ".workflow",
    "WorkflowBase": ".workflowbase",
    "WorkflowBaseTypedDict": ".workflowbase",
    "WorkflowStatus": ".workflowstatus",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
