"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .authmethod import AuthMethod
from .granttype import GrantType
from lineart_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class AuthConfigTypedDict(TypedDict):
    r"""Unified authentication configuration for DataSources.

    The auth config defines HOW to authenticate (method, endpoints, etc).
    The actual credentials (CLIENT_ID, CLIENT_SECRET) are configured separately
    via environment variables and stored securely in the database.

    Configuration Flow:
    1. User creates DataSource with AuthConfig (this object)
    2. User separately sets CLIENT_ID and CLIENT_SECRET as env vars
    3. Backend stores credentials securely (CLIENT_SECRET encrypted)
    4. At runtime, credentials are retrieved and used with this auth config
    """

    method: AuthMethod
    token_url: NotRequired[Nullable[str]]
    r"""OAuth token endpoint URL (required for bearer auth)"""
    grant_type: NotRequired[Nullable[GrantType]]
    r"""OAuth grant type (required for bearer auth)"""
    scope: NotRequired[Nullable[str]]
    r"""OAuth scope - space-separated list (optional)"""


class AuthConfig(BaseModel):
    r"""Unified authentication configuration for DataSources.

    The auth config defines HOW to authenticate (method, endpoints, etc).
    The actual credentials (CLIENT_ID, CLIENT_SECRET) are configured separately
    via environment variables and stored securely in the database.

    Configuration Flow:
    1. User creates DataSource with AuthConfig (this object)
    2. User separately sets CLIENT_ID and CLIENT_SECRET as env vars
    3. Backend stores credentials securely (CLIENT_SECRET encrypted)
    4. At runtime, credentials are retrieved and used with this auth config
    """

    method: AuthMethod

    token_url: OptionalNullable[str] = UNSET
    r"""OAuth token endpoint URL (required for bearer auth)"""

    grant_type: OptionalNullable[GrantType] = UNSET
    r"""OAuth grant type (required for bearer auth)"""

    scope: OptionalNullable[str] = UNSET
    r"""OAuth scope - space-separated list (optional)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["token_url", "grant_type", "scope"]
        nullable_fields = ["token_url", "grant_type", "scope"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
