"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from lineart_sdk.types import BaseModel


class AuthUserInfoResponseTypedDict(TypedDict):
    email: str
    picture: str


class AuthUserInfoResponse(BaseModel):
    email: str

    picture: str
