"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lineart_sdk.types import BaseModel
from typing_extensions import TypedDict


class AuthUserInfoResponseTypedDict(TypedDict):
    email: str
    picture: str


class AuthUserInfoResponse(BaseModel):
    email: str

    picture: str
