"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from lineart_sdk.types import BaseModel


class AuthDisconnectResponseTypedDict(TypedDict):
    message: str


class AuthDisconnectResponse(BaseModel):
    message: str
