"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Any, Dict, Optional

from typing_extensions import NotRequired, TypedDict

from lineart_sdk.types import BaseModel


class BodyRunVersionSyncTypedDict(TypedDict):
    policy_version_id: str
    input_data: Dict[str, Any]
    config_variables: NotRequired[Dict[str, Any]]


class BodyRunVersionSync(BaseModel):
    policy_version_id: str

    input_data: Dict[str, Any]

    config_variables: Optional[Dict[str, Any]] = None
