"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lineart_sdk.types import BaseModel
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class BodyRunWorkflowTypedDict(TypedDict):
    input_data: Dict[str, Any]
    config_variables: NotRequired[Dict[str, Any]]


class BodyRunWorkflow(BaseModel):
    input_data: Dict[str, Any]

    config_variables: Optional[Dict[str, Any]] = None
