"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Optional

from typing_extensions import NotRequired, TypedDict

from lineart_sdk.types import BaseModel


class CachingTTLTypedDict(TypedDict):
    days: NotRequired[int]
    hours: NotRequired[int]
    minutes: NotRequired[int]
    seconds: NotRequired[int]


class CachingTTL(BaseModel):
    days: Optional[int] = 0

    hours: Optional[int] = 0

    minutes: Optional[int] = 0

    seconds: Optional[int] = 0
