"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dataobjectorigin import DataObjectOrigin
from lineart_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Any, Dict, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


DataBrokerResponseErrorTypedDict = TypeAliasType(
    "DataBrokerResponseErrorTypedDict", Union[Dict[str, Any], str]
)


DataBrokerResponseError = TypeAliasType(
    "DataBrokerResponseError", Union[Dict[str, Any], str]
)


class DataBrokerResponseTypedDict(TypedDict):
    data_object_id: str
    origin: DataObjectOrigin
    key: str
    value: Any
    start_time: NotRequired[Nullable[float]]
    end_time: NotRequired[Nullable[float]]
    error: NotRequired[Nullable[DataBrokerResponseErrorTypedDict]]


class DataBrokerResponse(BaseModel):
    data_object_id: str

    origin: DataObjectOrigin

    key: str

    value: Any

    start_time: OptionalNullable[float] = UNSET

    end_time: OptionalNullable[float] = UNSET

    error: OptionalNullable[DataBrokerResponseError] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["start_time", "end_time", "error"]
        nullable_fields = ["start_time", "end_time", "error"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
