"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from lineart_sdk.types import BaseModel
from typing_extensions import TypedDict


class DataObjectMetadataTypedDict(TypedDict):
    data_object_id: str
    data_source_id: str
    key: str
    created_at: datetime


class DataObjectMetadata(BaseModel):
    data_object_id: str

    data_source_id: str

    key: str

    created_at: datetime
