"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Any, Dict, Optional, Union

from pydantic import model_serializer
from typing_extensions import NotRequired, TypeAliasType, TypedDict

from lineart_sdk.types import (
    UNSET,
    UNSET_SENTINEL,
    BaseModel,
    Nullable,
    OptionalNullable,
)

DataSourceTestRequestBodyTypedDict = TypeAliasType(
    "DataSourceTestRequestBodyTypedDict", Union[Dict[str, Any], str]
)


DataSourceTestRequestBody = TypeAliasType(
    "DataSourceTestRequestBody", Union[Dict[str, Any], str]
)


class DataSourceTestRequestTypedDict(TypedDict):
    r"""Full test request with all configuration (used for testing without existing data source)."""

    url: str
    method: NotRequired[str]
    headers: NotRequired[Nullable[Dict[str, str]]]
    body: NotRequired[Nullable[DataSourceTestRequestBodyTypedDict]]
    params: NotRequired[Nullable[Dict[str, Any]]]
    env_vars: NotRequired[Nullable[Dict[str, str]]]


class DataSourceTestRequest(BaseModel):
    r"""Full test request with all configuration (used for testing without existing data source)."""

    url: str

    method: Optional[str] = "GET"

    headers: OptionalNullable[Dict[str, str]] = UNSET

    body: OptionalNullable[DataSourceTestRequestBody] = UNSET

    params: OptionalNullable[Dict[str, Any]] = UNSET

    env_vars: OptionalNullable[Dict[str, str]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["method", "headers", "body", "params", "env_vars"]
        nullable_fields = ["headers", "body", "params", "env_vars"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
