"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from lineart_sdk.types import BaseModel
from typing_extensions import TypedDict


class DataSourceReferenceTypedDict(TypedDict):
    data_source_id: str
    name: str
    created_at: datetime


class DataSourceReference(BaseModel):
    data_source_id: str

    name: str

    created_at: datetime
