"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from lineart_sdk.types import BaseModel
from typing_extensions import TypedDict


class DataSourceCredentialCredentialType(str, Enum):
    CLIENT_ID = "CLIENT_ID"
    CLIENT_SECRET = "CLIENT_SECRET"
    USERNAME = "USERNAME"
    PASSWORD = "PASSWORD"


class DataSourceCredentialTypedDict(TypedDict):
    credential_type: DataSourceCredentialCredentialType
    value: str
    credential_id: str
    data_source_id: str
    created_at: datetime
    last_updated_at: datetime


class DataSourceCredential(BaseModel):
    credential_type: DataSourceCredentialCredentialType

    value: str

    credential_id: str

    data_source_id: str

    created_at: datetime

    last_updated_at: datetime
