"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .datasourcetestparams import DataSourceTestParams, DataSourceTestParamsTypedDict
from lineart_sdk.types import BaseModel
from lineart_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class DataSourceTestByIDRequestTypedDict(TypedDict):
    data_source_id: str
    data_source_test_params: DataSourceTestParamsTypedDict


class DataSourceTestByIDRequest(BaseModel):
    data_source_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    data_source_test_params: Annotated[
        DataSourceTestParams,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
