"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Any, Dict

from typing_extensions import TypedDict

from lineart_sdk.types import BaseModel


class DataBrokerRequestTypedDict(TypedDict):
    data_source_name: str
    configured_params: Dict[str, Any]
    run_id: str


class DataBrokerRequest(BaseModel):
    data_source_name: str

    configured_params: Dict[str, Any]

    run_id: str
