"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .authconfig import AuthConfig, AuthConfigTypedDict
from .retrypolicy import RetryPolicy, RetryPolicyTypedDict
from enum import Enum
from lineart_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class Method(str, Enum):
    GET = "GET"
    POST = "POST"
    PUT = "PUT"
    DELETE = "DELETE"


class ResponseType(str, Enum):
    JSON = "JSON"
    XML = "XML"
    CSV = "CSV"
    PLAIN_TEXT = "PLAIN_TEXT"


class HTTPSourceTypedDict(TypedDict):
    r"""HTTP data source configuration with optional authentication."""

    url: str
    method: NotRequired[Method]
    headers: NotRequired[Dict[str, Any]]
    params: NotRequired[Dict[str, Any]]
    body: NotRequired[Dict[str, Any]]
    timeout: NotRequired[Nullable[int]]
    retry: NotRequired[RetryPolicyTypedDict]
    response_type: NotRequired[ResponseType]
    auth: NotRequired[Nullable[AuthConfigTypedDict]]


class HTTPSource(BaseModel):
    r"""HTTP data source configuration with optional authentication."""

    url: str

    method: Optional[Method] = Method.GET

    headers: Optional[Dict[str, Any]] = None

    params: Optional[Dict[str, Any]] = None

    body: Optional[Dict[str, Any]] = None

    timeout: OptionalNullable[int] = UNSET

    retry: Optional[RetryPolicy] = None

    response_type: Optional[ResponseType] = ResponseType.PLAIN_TEXT

    auth: OptionalNullable[AuthConfig] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "method",
            "headers",
            "params",
            "body",
            "timeout",
            "retry",
            "response_type",
            "auth",
        ]
        nullable_fields = ["timeout", "auth"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
