"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dependencydict import DependencyDict, DependencyDictTypedDict
from lineart_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Any, Dict, List
from typing_extensions import NotRequired, TypedDict


class NodeDefinitionDictTypedDict(TypedDict):
    r"""Dict representation of a NodeDefinition object."""

    name: str
    node_type: str
    dependencies: NotRequired[Nullable[Dict[str, DependencyDictTypedDict]]]
    metadata: NotRequired[Nullable[Dict[str, Any]]]
    description: NotRequired[Nullable[str]]
    hierarchy: NotRequired[Nullable[List[str]]]


class NodeDefinitionDict(BaseModel):
    r"""Dict representation of a NodeDefinition object."""

    name: str

    node_type: str

    dependencies: OptionalNullable[Dict[str, DependencyDict]] = UNSET

    metadata: OptionalNullable[Dict[str, Any]] = UNSET

    description: OptionalNullable[str] = UNSET

    hierarchy: OptionalNullable[List[str]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["dependencies", "metadata", "description", "hierarchy"]
        nullable_fields = ["dependencies", "metadata", "description", "hierarchy"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
