"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing import Optional

from typing_extensions import NotRequired, TypedDict

from lineart_sdk.types import BaseModel


class PolicyCreateTypedDict(TypedDict):
    name: str
    description: NotRequired[str]


class PolicyCreate(BaseModel):
    name: str

    description: Optional[str] = ""
