"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from lineart_sdk.types import BaseModel


class PolicyRunPartitionTypedDict(TypedDict):
    policy_version_id: str
    frequency: int


class PolicyRunPartition(BaseModel):
    policy_version_id: str

    frequency: int
