"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from lineart_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PolicyCreateTypedDict(TypedDict):
    name: str
    description: NotRequired[str]


class PolicyCreate(BaseModel):
    name: str

    description: Optional[str] = ""
