"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .stepmetadatabase import StepMetadataBase, StepMetadataBaseTypedDict
from lineart_sdk.types import BaseModel
from lineart_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PublishMetadataRequestTypedDict(TypedDict):
    run_id: str
    step_metadata_base: StepMetadataBaseTypedDict


class PublishMetadataRequest(BaseModel):
    run_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    step_metadata_base: Annotated[
        StepMetadataBase,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
