"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import Annotated, TypedDict

from lineart_sdk.types import BaseModel
from lineart_sdk.utils import FieldMetadata, PathParamMetadata


class PublishDataSourceRequestTypedDict(TypedDict):
    data_source_id: str


class PublishDataSourceRequest(BaseModel):
    data_source_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
