"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .body_run_version_sync import BodyRunVersionSync, BodyRunVersionSyncTypedDict
from lineart_sdk.types import BaseModel
from lineart_sdk.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RunVersionSyncRequestTypedDict(TypedDict):
    body_run_version_sync: BodyRunVersionSyncTypedDict
    polling_interval_ms: NotRequired[int]
    polling_timeout_ms: NotRequired[int]


class RunVersionSyncRequest(BaseModel):
    body_run_version_sync: Annotated[
        BodyRunVersionSync,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    polling_interval_ms: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 500

    polling_timeout_ms: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 300000
