"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .body_run_workflow import BodyRunWorkflow, BodyRunWorkflowTypedDict
from lineart_sdk.types import BaseModel
from lineart_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RunWorkflowRequestTypedDict(TypedDict):
    policy_version_id: str
    body_run_workflow: BodyRunWorkflowTypedDict
    polling_interval_ms: NotRequired[int]
    polling_timeout_ms: NotRequired[int]


class RunWorkflowRequest(BaseModel):
    policy_version_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body_run_workflow: Annotated[
        BodyRunWorkflow,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    polling_interval_ms: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 500

    polling_timeout_ms: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 300000
