"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from lineart_sdk.types import BaseModel


class RunCreatedTypedDict(TypedDict):
    policy_version_id: str
    run_id: str


class RunCreated(BaseModel):
    policy_version_id: str

    run_id: str
