"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .rungroupruns import RunGroupRuns, RunGroupRunsTypedDict
from lineart_sdk.types import BaseModel
from typing_extensions import TypedDict


class RunGroupResultTypedDict(TypedDict):
    policy_id: str
    run_group_id: str
    runs: RunGroupRunsTypedDict


class RunGroupResult(BaseModel):
    policy_id: str

    run_group_id: str

    runs: RunGroupRuns
