"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import TypedDict

from lineart_sdk.types import BaseModel

from .rungroupruns import RunGroupRuns, RunGroupRunsTypedDict


class RunGroupResultTypedDict(TypedDict):
    policy_id: str
    run_group_id: str
    runs: RunGroupRunsTypedDict


class RunGroupResult(BaseModel):
    policy_id: str

    run_group_id: str

    runs: RunGroupRuns
