"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from datetime import datetime
from typing import List

from typing_extensions import TypedDict

from lineart_sdk.types import BaseModel

from .logentry import LogEntry, LogEntryTypedDict


class RunLogsTypedDict(TypedDict):
    run_id: str
    status: str
    last_updated_at: datetime
    logs: List[LogEntryTypedDict]


class RunLogs(BaseModel):
    run_id: str

    status: str

    last_updated_at: datetime

    logs: List[LogEntry]
