"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .logentry import LogEntry, LogEntryTypedDict
from datetime import datetime
from lineart_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class RunLogsTypedDict(TypedDict):
    run_id: str
    status: str
    last_updated_at: datetime
    logs: List[LogEntryTypedDict]


class RunLogs(BaseModel):
    run_id: str

    status: str

    last_updated_at: datetime

    logs: List[LogEntry]
