"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .body_runs_outcomes_by_policy import (
    BodyRunsOutcomesByPolicy,
    BodyRunsOutcomesByPolicyTypedDict,
)
from datetime import date
from lineart_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from lineart_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RunsOutcomesByPolicyRequestTypedDict(TypedDict):
    policy_id: str
    start_date: NotRequired[Nullable[date]]
    end_date: NotRequired[Nullable[date]]
    body_runs_outcomes_by_policy: NotRequired[BodyRunsOutcomesByPolicyTypedDict]


class RunsOutcomesByPolicyRequest(BaseModel):
    policy_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    start_date: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET

    end_date: Annotated[
        OptionalNullable[date],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET

    body_runs_outcomes_by_policy: Annotated[
        Optional[BodyRunsOutcomesByPolicy],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["start_date", "end_date", "Body_runs_outcomes_by_policy"]
        nullable_fields = ["start_date", "end_date"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
