"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .configurationvariablesbase import (
    ConfigurationVariablesBase,
    ConfigurationVariablesBaseTypedDict,
)
from lineart_sdk.types import BaseModel
from lineart_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import List
from typing_extensions import Annotated, TypedDict


class SetConfigVariablesRequestTypedDict(TypedDict):
    policy_version_id: str
    request_body: List[ConfigurationVariablesBaseTypedDict]


class SetConfigVariablesRequest(BaseModel):
    policy_version_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        List[ConfigurationVariablesBase],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
