"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .stepmetadatabase import StepMetadataBase, StepMetadataBaseTypedDict
from lineart_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict, List, Union
from typing_extensions import TypeAliasType, TypedDict


OutputTypedDict = TypeAliasType(
    "OutputTypedDict", Union[bytes, str, Dict[str, Any], List[Any], int, float]
)


Output = TypeAliasType(
    "Output", Union[bytes, str, Dict[str, Any], List[Any], int, float]
)


class StepDetailsTypedDict(TypedDict):
    output: Nullable[OutputTypedDict]
    metadata: Nullable[StepMetadataBaseTypedDict]


class StepDetails(BaseModel):
    output: Nullable[Output]

    metadata: Nullable[StepMetadataBase]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = []
        nullable_fields = ["output", "metadata"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
