"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .uinodeposition import UINodePosition, UINodePositionTypedDict
from lineart_sdk.types import BaseModel
from typing_extensions import TypedDict


class UIMetadataTypedDict(TypedDict):
    position: UINodePositionTypedDict
    width: float
    height: float


class UIMetadata(BaseModel):
    position: UINodePosition

    width: float

    height: float
