"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import Annotated, TypedDict

from lineart_sdk.types import BaseModel
from lineart_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata

from .policyversionupdate import PolicyVersionUpdate, PolicyVersionUpdateTypedDict


class UpdatePolicyVersionRequestTypedDict(TypedDict):
    policy_version_id: str
    policy_version_update: PolicyVersionUpdateTypedDict


class UpdatePolicyVersionRequest(BaseModel):
    policy_version_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    policy_version_update: Annotated[
        PolicyVersionUpdate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
