"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .body_update_run import BodyUpdateRun, BodyUpdateRunTypedDict
from lineart_sdk.types import BaseModel
from lineart_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UpdateRunRequestTypedDict(TypedDict):
    run_id: str
    body_update_run: BodyUpdateRunTypedDict


class UpdateRunRequest(BaseModel):
    run_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    body_update_run: Annotated[
        BodyUpdateRun,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
