"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations

from typing_extensions import Annotated, TypedDict

from lineart_sdk.types import BaseModel
from lineart_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata

from .policybase import PolicyBase, PolicyBaseTypedDict


class UpdatePolicyRequestTypedDict(TypedDict):
    policy_id: str
    policy_base: PolicyBaseTypedDict


class UpdatePolicyRequest(BaseModel):
    policy_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    policy_base: Annotated[
        PolicyBase,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
