repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-added-large-files
  - id: detect-private-key
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.1
  hooks:
    # Run the linter.
    - id: ruff
      entry: ruff check
      args: [ --force-exclude, --select, I, --fix]
      types_or: [ python, pyi, jupyter ]
    # Run the formatter.
    - id: ruff-format
      entry: ruff format 
      args: [--force-exclude]
      types_or: [ python, pyi, jupyter ]