steps:
  - name: python
    entrypoint: python
    args: ['-m', 'pip', 'install', '--upgrade',  'pip', 'build', 'twine', 'keyrings.google-artifactregistry-auth', '--user']

  - name: python
    entrypoint: python
    args: ['-m', 'build', 'vulkan-public']

  - name: python
    entrypoint: python
    args: ['-m', 'build', 'vulkan']
  
  - name: python
    entrypoint: python
    args:
    - '-m'
    - 'twine'
    - 'upload'
    - '--skip-existing'
    - '--repository-url'
    - 'https://${_LOCATION}-python.pkg.dev/$PROJECT_ID/${_REPOSITORY}/'
    - '/workspace/vulkan-public/dist/*'
    - '/workspace/vulkan/dist/*'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t',
        '${_DOCKER_REPOSITORY_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REPOSITORY_NAME}/metrics-pipeline:latest',
        '-f',
        '/workspace/images/beam/metrics.Dockerfile',
        '.'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
