/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BodyCreateRunGroup
 */
export interface BodyCreateRunGroup {
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof BodyCreateRunGroup
   */
  input_data: { [key: string]: any };
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof BodyCreateRunGroup
   */
  config_variables?: { [key: string]: any };
}

/**
 * Check if a given object implements the BodyCreateRunGroup interface.
 */
export function instanceOfBodyCreateRunGroup(
  value: object,
): value is BodyCreateRunGroup {
  if (!("input_data" in value) || value["input_data"] === undefined)
    return false;
  return true;
}

export function BodyCreateRunGroupFromJSON(json: any): BodyCreateRunGroup {
  return BodyCreateRunGroupFromJSONTyped(json, false);
}

export function BodyCreateRunGroupFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BodyCreateRunGroup {
  if (json == null) {
    return json;
  }
  return {
    input_data: json["input_data"],
    config_variables:
      json["config_variables"] == null ? undefined : json["config_variables"],
  };
}

export function BodyCreateRunGroupToJSON(json: any): BodyCreateRunGroup {
  return BodyCreateRunGroupToJSONTyped(json, false);
}

export function BodyCreateRunGroupToJSONTyped(
  value?: BodyCreateRunGroup | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    input_data: value["input_data"],
    config_variables: value["config_variables"],
  };
}
