/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BodyCreateRunByPolicyVersion
 */
export interface BodyCreateRunByPolicyVersion {
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof BodyCreateRunByPolicyVersion
   */
  input_data: { [key: string]: any };
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof BodyCreateRunByPolicyVersion
   */
  config_variables?: { [key: string]: any };
}

/**
 * Check if a given object implements the BodyCreateRunByPolicyVersion interface.
 */
export function instanceOfBodyCreateRunByPolicyVersion(
  value: object,
): value is BodyCreateRunByPolicyVersion {
  if (!("input_data" in value) || value["input_data"] === undefined)
    return false;
  return true;
}

export function BodyCreateRunByPolicyVersionFromJSON(
  json: any,
): BodyCreateRunByPolicyVersion {
  return BodyCreateRunByPolicyVersionFromJSONTyped(json, false);
}

export function BodyCreateRunByPolicyVersionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BodyCreateRunByPolicyVersion {
  if (json == null) {
    return json;
  }
  return {
    input_data: json["input_data"],
    config_variables:
      json["config_variables"] == null ? undefined : json["config_variables"],
  };
}

export function BodyCreateRunByPolicyVersionToJSON(
  json: any,
): BodyCreateRunByPolicyVersion {
  return BodyCreateRunByPolicyVersionToJSONTyped(json, false);
}

export function BodyCreateRunByPolicyVersionToJSONTyped(
  value?: BodyCreateRunByPolicyVersion | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    input_data: value["input_data"],
    config_variables: value["config_variables"],
  };
}
