/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DataSourceReference
 */
export interface DataSourceReference {
  /**
   *
   * @type {string}
   * @memberof DataSourceReference
   */
  data_source_id: string;
  /**
   *
   * @type {string}
   * @memberof DataSourceReference
   */
  name: string;
  /**
   *
   * @type {Date}
   * @memberof DataSourceReference
   */
  created_at: Date;
}

/**
 * Check if a given object implements the DataSourceReference interface.
 */
export function instanceOfDataSourceReference(
  value: object,
): value is DataSourceReference {
  if (!("data_source_id" in value) || value["data_source_id"] === undefined)
    return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("created_at" in value) || value["created_at"] === undefined)
    return false;
  return true;
}

export function DataSourceReferenceFromJSON(json: any): DataSourceReference {
  return DataSourceReferenceFromJSONTyped(json, false);
}

export function DataSourceReferenceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DataSourceReference {
  if (json == null) {
    return json;
  }
  return {
    data_source_id: json["data_source_id"],
    name: json["name"],
    created_at: new Date(json["created_at"]),
  };
}

export function DataSourceReferenceToJSON(json: any): DataSourceReference {
  return DataSourceReferenceToJSONTyped(json, false);
}

export function DataSourceReferenceToJSONTyped(
  value?: DataSourceReference | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data_source_id: value["data_source_id"],
    name: value["name"],
    created_at: value["created_at"].toISOString(),
  };
}
