/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const DataObjectOrigin = {
  Request: "REQUEST",
  Cache: "CACHE",
} as const;
export type DataObjectOrigin =
  (typeof DataObjectOrigin)[keyof typeof DataObjectOrigin];

export function instanceOfDataObjectOrigin(value: any): boolean {
  for (const key in DataObjectOrigin) {
    if (Object.prototype.hasOwnProperty.call(DataObjectOrigin, key)) {
      if (DataObjectOrigin[key as keyof typeof DataObjectOrigin] === value) {
        return true;
      }
    }
  }
  return false;
}

export function DataObjectOriginFromJSON(json: any): DataObjectOrigin {
  return DataObjectOriginFromJSONTyped(json, false);
}

export function DataObjectOriginFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DataObjectOrigin {
  return json as DataObjectOrigin;
}

export function DataObjectOriginToJSON(value?: DataObjectOrigin | null): any {
  return value as any;
}

export function DataObjectOriginToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): DataObjectOrigin {
  return value as DataObjectOrigin;
}
