/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DataObject
 */
export interface DataObject {
  /**
   *
   * @type {string}
   * @memberof DataObject
   */
  data_object_id: string;
  /**
   *
   * @type {string}
   * @memberof DataObject
   */
  data_source_id: string;
  /**
   *
   * @type {string}
   * @memberof DataObject
   */
  project_id: string;
  /**
   *
   * @type {string}
   * @memberof DataObject
   */
  key: string;
  /**
   *
   * @type {Date}
   * @memberof DataObject
   */
  created_at: Date;
  /**
   *
   * @type {any}
   * @memberof DataObject
   */
  value: any | null;
}

/**
 * Check if a given object implements the DataObject interface.
 */
export function instanceOfDataObject(value: object): value is DataObject {
  if (!("data_object_id" in value) || value["data_object_id"] === undefined)
    return false;
  if (!("data_source_id" in value) || value["data_source_id"] === undefined)
    return false;
  if (!("project_id" in value) || value["project_id"] === undefined)
    return false;
  if (!("key" in value) || value["key"] === undefined) return false;
  if (!("created_at" in value) || value["created_at"] === undefined)
    return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function DataObjectFromJSON(json: any): DataObject {
  return DataObjectFromJSONTyped(json, false);
}

export function DataObjectFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DataObject {
  if (json == null) {
    return json;
  }
  return {
    data_object_id: json["data_object_id"],
    data_source_id: json["data_source_id"],
    project_id: json["project_id"],
    key: json["key"],
    created_at: new Date(json["created_at"]),
    value: json["value"],
  };
}

export function DataObjectToJSON(json: any): DataObject {
  return DataObjectToJSONTyped(json, false);
}

export function DataObjectToJSONTyped(
  value?: DataObject | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data_object_id: value["data_object_id"],
    data_source_id: value["data_source_id"],
    project_id: value["project_id"],
    key: value["key"],
    created_at: value["created_at"].toISOString(),
    value: value["value"],
  };
}
