/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EnvVarConfig
 */
export interface EnvVarConfig {
  /**
   *
   * @type {string}
   * @memberof EnvVarConfig
   */
  env: string;
}

/**
 * Check if a given object implements the EnvVarConfig interface.
 */
export function instanceOfEnvVarConfig(value: object): value is EnvVarConfig {
  if (!("env" in value) || value["env"] === undefined) return false;
  return true;
}

export function EnvVarConfigFromJSON(json: any): EnvVarConfig {
  return EnvVarConfigFromJSONTyped(json, false);
}

export function EnvVarConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EnvVarConfig {
  if (json == null) {
    return json;
  }
  return {
    env: json["env"],
  };
}

export function EnvVarConfigToJSON(json: any): EnvVarConfig {
  return EnvVarConfigToJSONTyped(json, false);
}

export function EnvVarConfigToJSONTyped(
  value?: EnvVarConfig | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    env: value["env"],
  };
}
