/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CachingTTL } from "./CachingTTL";
import {
  CachingTTLFromJSON,
  CachingTTLFromJSONTyped,
  CachingTTLToJSON,
  CachingTTLToJSONTyped,
} from "./CachingTTL";

/**
 *
 * @export
 * @interface Ttl
 */
export interface Ttl {
  /**
   *
   * @type {number}
   * @memberof Ttl
   */
  days?: number;
  /**
   *
   * @type {number}
   * @memberof Ttl
   */
  hours?: number;
  /**
   *
   * @type {number}
   * @memberof Ttl
   */
  minutes?: number;
  /**
   *
   * @type {number}
   * @memberof Ttl
   */
  seconds?: number;
}

/**
 * Check if a given object implements the Ttl interface.
 */
export function instanceOfTtl(value: object): value is Ttl {
  return true;
}

export function TtlFromJSON(json: any): Ttl {
  return TtlFromJSONTyped(json, false);
}

export function TtlFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ttl {
  if (json == null) {
    return json;
  }
  return {
    days: json["days"] == null ? undefined : json["days"],
    hours: json["hours"] == null ? undefined : json["hours"],
    minutes: json["minutes"] == null ? undefined : json["minutes"],
    seconds: json["seconds"] == null ? undefined : json["seconds"],
  };
}

export function TtlToJSON(json: any): Ttl {
  return TtlToJSONTyped(json, false);
}

export function TtlToJSONTyped(
  value?: Ttl | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    days: value["days"],
    hours: value["hours"],
    minutes: value["minutes"],
    seconds: value["seconds"],
  };
}
