name: "💡 Feature Request"
description: Create a feature request
title: "💡 [REQUEST] - <title>"
labels: [
  "feature_request"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe your feature request in a few lines 
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Give an example of how this feature would work and what it would allow you to do.
      placeholder: A few specific words about your feature request.
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "Drawbacks"
      description: What are the drawbacks/impacts of your feature request?
      placeholder: Identify the drawbacks and impacts
    validations:
      required: true
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved?
      placeholder: Identify any unresolved issues.
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Related Issues"
      description: Issues related to the feature described
      placeholder: "#Issue IDs"
    validations:
      required: false
  - type: textarea
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: Pull request that implements this feature
      placeholder: "#Pull Request ID"
    validations:
      required: false
  