# storage:
#   sqlite:
#     base_dir:

run_launcher:
  module: dagster.core.launcher
  class: DefaultRunLauncher
# run_coordinator:
#   module: dagster.core.run_coordinator
#   class: DefaultRunCoordinator
telemetry:
  enabled: false
