[tool.poetry]
name = "engine"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
fastapi = "^0.112.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
