/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BacktestMetricsConfig
 */
export interface BacktestMetricsConfig {
    /**
     * 
     * @type {string}
     * @memberof BacktestMetricsConfig
     */
    target_column: string;
    /**
     * 
     * @type {string}
     * @memberof BacktestMetricsConfig
     */
    time_column?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof BacktestMetricsConfig
     */
    group_by_columns?: Array<string> | null;
}

/**
 * Check if a given object implements the BacktestMetricsConfig interface.
 */
export function instanceOfBacktestMetricsConfig(value: object): value is BacktestMetricsConfig {
    if (!('target_column' in value) || value['target_column'] === undefined) return false;
    return true;
}

export function BacktestMetricsConfigFromJSON(json: any): BacktestMetricsConfig {
    return BacktestMetricsConfigFromJSONTyped(json, false);
}

export function BacktestMetricsConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): BacktestMetricsConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'target_column': json['target_column'],
        'time_column': json['time_column'] == null ? undefined : json['time_column'],
        'group_by_columns': json['group_by_columns'] == null ? undefined : json['group_by_columns'],
    };
}

export function BacktestMetricsConfigToJSON(json: any): BacktestMetricsConfig {
    return BacktestMetricsConfigToJSONTyped(json, false);
}

export function BacktestMetricsConfigToJSONTyped(value?: BacktestMetricsConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_column': value['target_column'],
        'time_column': value['time_column'],
        'group_by_columns': value['group_by_columns'],
    };
}

