/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface BodyUpdateRun
 */
export interface BodyUpdateRun {
  /**
   *
   * @type {string}
   * @memberof BodyUpdateRun
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof BodyUpdateRun
   */
  result: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof BodyUpdateRun
   */
  metadata?: { [key: string]: any } | null;
}

/**
 * Check if a given object implements the BodyUpdateRun interface.
 */
export function instanceOfBodyUpdateRun(value: object): value is BodyUpdateRun {
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("result" in value) || value["result"] === undefined) return false;
  return true;
}

export function BodyUpdateRunFromJSON(json: any): BodyUpdateRun {
  return BodyUpdateRunFromJSONTyped(json, false);
}

export function BodyUpdateRunFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BodyUpdateRun {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    result: json["result"],
    metadata: json["metadata"] == null ? undefined : json["metadata"],
  };
}

export function BodyUpdateRunToJSON(json: any): BodyUpdateRun {
  return BodyUpdateRunToJSONTyped(json, false);
}

export function BodyUpdateRunToJSONTyped(
  value?: BodyUpdateRun | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    result: value["result"],
    metadata: value["metadata"],
  };
}
