/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BodyRunsByPolicy
 */
export interface BodyRunsByPolicy {
    /**
     * 
     * @type {Array<string>}
     * @memberof BodyRunsByPolicy
     */
    versions?: Array<string> | null;
}

/**
 * Check if a given object implements the BodyRunsByPolicy interface.
 */
export function instanceOfBodyRunsByPolicy(value: object): value is BodyRunsByPolicy {
    return true;
}

export function BodyRunsByPolicyFromJSON(json: any): BodyRunsByPolicy {
    return BodyRunsByPolicyFromJSONTyped(json, false);
}

export function BodyRunsByPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyRunsByPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'versions': json['versions'] == null ? undefined : json['versions'],
    };
}

export function BodyRunsByPolicyToJSON(json: any): BodyRunsByPolicy {
    return BodyRunsByPolicyToJSONTyped(json, false);
}

export function BodyRunsByPolicyToJSONTyped(value?: BodyRunsByPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'versions': value['versions'],
    };
}

