/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BacktestMetricsConfig } from './BacktestMetricsConfig';
import {
    BacktestMetricsConfigFromJSON,
    BacktestMetricsConfigFromJSONTyped,
    BacktestMetricsConfigToJSON,
    BacktestMetricsConfigToJSONTyped,
} from './BacktestMetricsConfig';

/**
 * 
 * @export
 * @interface BodyLaunchBacktest
 */
export interface BodyLaunchBacktest {
    /**
     * 
     * @type {string}
     * @memberof BodyLaunchBacktest
     */
    policy_version_id: string;
    /**
     * 
     * @type {string}
     * @memberof BodyLaunchBacktest
     */
    input_file_id: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof BodyLaunchBacktest
     */
    config_variables: Array<{ [key: string]: any; }> | null;
    /**
     * 
     * @type {BacktestMetricsConfig}
     * @memberof BodyLaunchBacktest
     */
    metrics_config?: BacktestMetricsConfig | null;
}

/**
 * Check if a given object implements the BodyLaunchBacktest interface.
 */
export function instanceOfBodyLaunchBacktest(value: object): value is BodyLaunchBacktest {
    if (!('policy_version_id' in value) || value['policy_version_id'] === undefined) return false;
    if (!('input_file_id' in value) || value['input_file_id'] === undefined) return false;
    if (!('config_variables' in value) || value['config_variables'] === undefined) return false;
    return true;
}

export function BodyLaunchBacktestFromJSON(json: any): BodyLaunchBacktest {
    return BodyLaunchBacktestFromJSONTyped(json, false);
}

export function BodyLaunchBacktestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyLaunchBacktest {
    if (json == null) {
        return json;
    }
    return {
        
        'policy_version_id': json['policy_version_id'],
        'input_file_id': json['input_file_id'],
        'config_variables': json['config_variables'] == null ? null : json['config_variables'],
        'metrics_config': json['metrics_config'] == null ? undefined : BacktestMetricsConfigFromJSON(json['metrics_config']),
    };
}

export function BodyLaunchBacktestToJSON(json: any): BodyLaunchBacktest {
    return BodyLaunchBacktestToJSONTyped(json, false);
}

export function BodyLaunchBacktestToJSONTyped(value?: BodyLaunchBacktest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'policy_version_id': value['policy_version_id'],
        'input_file_id': value['input_file_id'],
        'config_variables': value['config_variables'],
        'metrics_config': BacktestMetricsConfigToJSON(value['metrics_config']),
    };
}

