/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ttl } from './Ttl';
import {
    TtlFromJSON,
    TtlFromJSONTyped,
    TtlToJSON,
    TtlToJSONTyped,
} from './Ttl';

/**
 * 
 * @export
 * @interface CachingOptions
 */
export interface CachingOptions {
    /**
     * 
     * @type {boolean}
     * @memberof CachingOptions
     */
    enabled?: boolean;
    /**
     * 
     * @type {Ttl}
     * @memberof CachingOptions
     */
    ttl?: Ttl | null;
}

/**
 * Check if a given object implements the CachingOptions interface.
 */
export function instanceOfCachingOptions(value: object): value is CachingOptions {
    return true;
}

export function CachingOptionsFromJSON(json: any): CachingOptions {
    return CachingOptionsFromJSONTyped(json, false);
}

export function CachingOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CachingOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'ttl': json['ttl'] == null ? undefined : TtlFromJSON(json['ttl']),
    };
}

export function CachingOptionsToJSON(json: any): CachingOptions {
    return CachingOptionsToJSONTyped(json, false);
}

export function CachingOptionsToJSONTyped(value?: CachingOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'ttl': TtlToJSON(value['ttl']),
    };
}

