/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Value } from './Value';
import {
    ValueFromJSON,
    ValueFromJSONTyped,
    ValueToJSON,
    ValueToJSONTyped,
} from './Value';

/**
 * 
 * @export
 * @interface ConfigurationVariables
 */
export interface ConfigurationVariables {
    /**
     * 
     * @type {string}
     * @memberof ConfigurationVariables
     */
    name: string;
    /**
     * 
     * @type {Value}
     * @memberof ConfigurationVariables
     */
    value?: Value | null;
    /**
     * 
     * @type {Date}
     * @memberof ConfigurationVariables
     */
    created_at?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ConfigurationVariables
     */
    last_updated_at?: Date | null;
}

/**
 * Check if a given object implements the ConfigurationVariables interface.
 */
export function instanceOfConfigurationVariables(value: object): value is ConfigurationVariables {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ConfigurationVariablesFromJSON(json: any): ConfigurationVariables {
    return ConfigurationVariablesFromJSONTyped(json, false);
}

export function ConfigurationVariablesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationVariables {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'] == null ? undefined : ValueFromJSON(json['value']),
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'last_updated_at': json['last_updated_at'] == null ? undefined : (new Date(json['last_updated_at'])),
    };
}

export function ConfigurationVariablesToJSON(json: any): ConfigurationVariables {
    return ConfigurationVariablesToJSONTyped(json, false);
}

export function ConfigurationVariablesToJSONTyped(value?: ConfigurationVariables | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': ValueToJSON(value['value']),
        'created_at': value['created_at'] === null ? null : ((value['created_at'] as any)?.toISOString()),
        'last_updated_at': value['last_updated_at'] === null ? null : ((value['last_updated_at'] as any)?.toISOString()),
    };
}

