/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DagsterLogDetails
 */
export interface DagsterLogDetails {
    /**
     * 
     * @type {string}
     * @memberof DagsterLogDetails
     */
    log_type: string;
    /**
     * 
     * @type {string}
     * @memberof DagsterLogDetails
     */
    message: string;
}

/**
 * Check if a given object implements the DagsterLogDetails interface.
 */
export function instanceOfDagsterLogDetails(value: object): value is DagsterLogDetails {
    if (!('log_type' in value) || value['log_type'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DagsterLogDetailsFromJSON(json: any): DagsterLogDetails {
    return DagsterLogDetailsFromJSONTyped(json, false);
}

export function DagsterLogDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DagsterLogDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'log_type': json['log_type'],
        'message': json['message'],
    };
}

export function DagsterLogDetailsToJSON(json: any): DagsterLogDetails {
    return DagsterLogDetailsToJSONTyped(json, false);
}

export function DagsterLogDetailsToJSONTyped(value?: DagsterLogDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'log_type': value['log_type'],
        'message': value['message'],
    };
}

