/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CachingOptions } from "./CachingOptions";
import {
  CachingOptionsFromJSON,
  CachingOptionsFromJSONTyped,
  CachingOptionsToJSON,
  CachingOptionsToJSONTyped,
} from "./CachingOptions";
import type { Source } from "./Source";
import {
  SourceFromJSON,
  SourceFromJSONTyped,
  SourceToJSON,
  SourceToJSONTyped,
} from "./Source";

/**
 *
 * @export
 * @interface DataSourceSpec
 */
export interface DataSourceSpec {
  /**
   *
   * @type {string}
   * @memberof DataSourceSpec
   */
  name: string;
  /**
   *
   * @type {Source}
   * @memberof DataSourceSpec
   */
  source: Source;
  /**
   *
   * @type {CachingOptions}
   * @memberof DataSourceSpec
   */
  caching?: CachingOptions;
  /**
   *
   * @type {string}
   * @memberof DataSourceSpec
   */
  description?: string | null;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof DataSourceSpec
   */
  metadata?: { [key: string]: any } | null;
}

/**
 * Check if a given object implements the DataSourceSpec interface.
 */
export function instanceOfDataSourceSpec(
  value: object,
): value is DataSourceSpec {
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("source" in value) || value["source"] === undefined) return false;
  return true;
}

export function DataSourceSpecFromJSON(json: any): DataSourceSpec {
  return DataSourceSpecFromJSONTyped(json, false);
}

export function DataSourceSpecFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DataSourceSpec {
  if (json == null) {
    return json;
  }
  return {
    name: json["name"],
    source: SourceFromJSON(json["source"]),
    caching:
      json["caching"] == null
        ? undefined
        : CachingOptionsFromJSON(json["caching"]),
    description: json["description"] == null ? undefined : json["description"],
    metadata: json["metadata"] == null ? undefined : json["metadata"],
  };
}

export function DataSourceSpecToJSON(json: any): DataSourceSpec {
  return DataSourceSpecToJSONTyped(json, false);
}

export function DataSourceSpecToJSONTyped(
  value?: DataSourceSpec | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    source: SourceToJSON(value["source"]),
    caching: CachingOptionsToJSON(value["caching"]),
    description: value["description"],
    metadata: value["metadata"],
  };
}
