/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DataObjectMetadata
 */
export interface DataObjectMetadata {
  /**
   *
   * @type {string}
   * @memberof DataObjectMetadata
   */
  data_object_id: string;
  /**
   *
   * @type {string}
   * @memberof DataObjectMetadata
   */
  data_source_id: string;
  /**
   *
   * @type {string}
   * @memberof DataObjectMetadata
   */
  project_id: string;
  /**
   *
   * @type {string}
   * @memberof DataObjectMetadata
   */
  key: string;
  /**
   *
   * @type {Date}
   * @memberof DataObjectMetadata
   */
  created_at: Date;
}

/**
 * Check if a given object implements the DataObjectMetadata interface.
 */
export function instanceOfDataObjectMetadata(
  value: object,
): value is DataObjectMetadata {
  if (!("data_object_id" in value) || value["data_object_id"] === undefined)
    return false;
  if (!("data_source_id" in value) || value["data_source_id"] === undefined)
    return false;
  if (!("project_id" in value) || value["project_id"] === undefined)
    return false;
  if (!("key" in value) || value["key"] === undefined) return false;
  if (!("created_at" in value) || value["created_at"] === undefined)
    return false;
  return true;
}

export function DataObjectMetadataFromJSON(json: any): DataObjectMetadata {
  return DataObjectMetadataFromJSONTyped(json, false);
}

export function DataObjectMetadataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DataObjectMetadata {
  if (json == null) {
    return json;
  }
  return {
    data_object_id: json["data_object_id"],
    data_source_id: json["data_source_id"],
    project_id: json["project_id"],
    key: json["key"],
    created_at: new Date(json["created_at"]),
  };
}

export function DataObjectMetadataToJSON(json: any): DataObjectMetadata {
  return DataObjectMetadataToJSONTyped(json, false);
}

export function DataObjectMetadataToJSONTyped(
  value?: DataObjectMetadata | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    data_object_id: value["data_object_id"],
    data_source_id: value["data_source_id"],
    project_id: value["project_id"],
    key: value["key"],
    created_at: value["created_at"].toISOString(),
  };
}
