/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataObjectOrigin } from './DataObjectOrigin';
import {
    DataObjectOriginFromJSON,
    DataObjectOriginFromJSONTyped,
    DataObjectOriginToJSON,
    DataObjectOriginToJSONTyped,
} from './DataObjectOrigin';

/**
 * 
 * @export
 * @interface DataBrokerResponse
 */
export interface DataBrokerResponse {
    /**
     * 
     * @type {string}
     * @memberof DataBrokerResponse
     */
    data_object_id: string;
    /**
     * 
     * @type {DataObjectOrigin}
     * @memberof DataBrokerResponse
     */
    origin: DataObjectOrigin;
    /**
     * 
     * @type {string}
     * @memberof DataBrokerResponse
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof DataBrokerResponse
     */
    value: any | null;
}



/**
 * Check if a given object implements the DataBrokerResponse interface.
 */
export function instanceOfDataBrokerResponse(value: object): value is DataBrokerResponse {
    if (!('data_object_id' in value) || value['data_object_id'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function DataBrokerResponseFromJSON(json: any): DataBrokerResponse {
    return DataBrokerResponseFromJSONTyped(json, false);
}

export function DataBrokerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataBrokerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data_object_id': json['data_object_id'],
        'origin': DataObjectOriginFromJSON(json['origin']),
        'key': json['key'],
        'value': json['value'],
    };
}

export function DataBrokerResponseToJSON(json: any): DataBrokerResponse {
    return DataBrokerResponseToJSONTyped(json, false);
}

export function DataBrokerResponseToJSONTyped(value?: DataBrokerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_object_id': value['data_object_id'],
        'origin': DataObjectOriginToJSON(value['origin']),
        'key': value['key'],
        'value': value['value'],
    };
}

