/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HTTPSourceHeadersValue } from './HTTPSourceHeadersValue';
import {
    HTTPSourceHeadersValueFromJSON,
    HTTPSourceHeadersValueFromJSONTyped,
    HTTPSourceHeadersValueToJSON,
    HTTPSourceHeadersValueToJSONTyped,
} from './HTTPSourceHeadersValue';
import type { RetryPolicy } from './RetryPolicy';
import {
    RetryPolicyFromJSON,
    RetryPolicyFromJSONTyped,
    RetryPolicyToJSON,
    RetryPolicyToJSONTyped,
} from './RetryPolicy';

/**
 * 
 * @export
 * @interface HTTPSource
 */
export interface HTTPSource {
    /**
     * 
     * @type {string}
     * @memberof HTTPSource
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof HTTPSource
     */
    method?: string;
    /**
     * 
     * @type {{ [key: string]: HTTPSourceHeadersValue; }}
     * @memberof HTTPSource
     */
    headers?: { [key: string]: HTTPSourceHeadersValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HTTPSourceHeadersValue; }}
     * @memberof HTTPSource
     */
    params?: { [key: string]: HTTPSourceHeadersValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HTTPSourceHeadersValue; }}
     * @memberof HTTPSource
     */
    body?: { [key: string]: HTTPSourceHeadersValue; } | null;
    /**
     * 
     * @type {number}
     * @memberof HTTPSource
     */
    timeout?: number | null;
    /**
     * 
     * @type {RetryPolicy}
     * @memberof HTTPSource
     */
    retry?: RetryPolicy | null;
    /**
     * 
     * @type {string}
     * @memberof HTTPSource
     */
    response_type?: string | null;
}

/**
 * Check if a given object implements the HTTPSource interface.
 */
export function instanceOfHTTPSource(value: object): value is HTTPSource {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function HTTPSourceFromJSON(json: any): HTTPSource {
    return HTTPSourceFromJSONTyped(json, false);
}

export function HTTPSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTTPSource {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'method': json['method'] == null ? undefined : json['method'],
        'headers': json['headers'] == null ? undefined : (mapValues(json['headers'], HTTPSourceHeadersValueFromJSON)),
        'params': json['params'] == null ? undefined : (mapValues(json['params'], HTTPSourceHeadersValueFromJSON)),
        'body': json['body'] == null ? undefined : (mapValues(json['body'], HTTPSourceHeadersValueFromJSON)),
        'timeout': json['timeout'] == null ? undefined : json['timeout'],
        'retry': json['retry'] == null ? undefined : RetryPolicyFromJSON(json['retry']),
        'response_type': json['response_type'] == null ? undefined : json['response_type'],
    };
}

export function HTTPSourceToJSON(json: any): HTTPSource {
    return HTTPSourceToJSONTyped(json, false);
}

export function HTTPSourceToJSONTyped(value?: HTTPSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'method': value['method'],
        'headers': value['headers'] == null ? undefined : (mapValues(value['headers'], HTTPSourceHeadersValueToJSON)),
        'params': value['params'] == null ? undefined : (mapValues(value['params'], HTTPSourceHeadersValueToJSON)),
        'body': value['body'] == null ? undefined : (mapValues(value['body'], HTTPSourceHeadersValueToJSON)),
        'timeout': value['timeout'],
        'retry': RetryPolicyToJSON(value['retry']),
        'response_type': value['response_type'],
    };
}

