/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Output
 */
export interface Output {
}

/**
 * Check if a given object implements the Output interface.
 */
export function instanceOfOutput(value: object): value is Output {
    return true;
}

export function OutputFromJSON(json: any): Output {
    return OutputFromJSONTyped(json, false);
}

export function OutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): Output {
    return json;
}

export function OutputToJSON(json: any): Output {
    return OutputToJSONTyped(json, false);
}

export function OutputToJSONTyped(value?: Output | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

