/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolicyVersionCreate
 */
export interface PolicyVersionCreate {
    /**
     * 
     * @type {string}
     * @memberof PolicyVersionCreate
     */
    policy_id: string;
    /**
     * 
     * @type {string}
     * @memberof PolicyVersionCreate
     */
    alias: string | null;
}

/**
 * Check if a given object implements the PolicyVersionCreate interface.
 */
export function instanceOfPolicyVersionCreate(value: object): value is PolicyVersionCreate {
    if (!('policy_id' in value) || value['policy_id'] === undefined) return false;
    if (!('alias' in value) || value['alias'] === undefined) return false;
    return true;
}

export function PolicyVersionCreateFromJSON(json: any): PolicyVersionCreate {
    return PolicyVersionCreateFromJSONTyped(json, false);
}

export function PolicyVersionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyVersionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'policy_id': json['policy_id'],
        'alias': json['alias'],
    };
}

export function PolicyVersionCreateToJSON(json: any): PolicyVersionCreate {
    return PolicyVersionCreateToJSONTyped(json, false);
}

export function PolicyVersionCreateToJSONTyped(value?: PolicyVersionCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'policy_id': value['policy_id'],
        'alias': value['alias'],
    };
}

