/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface PolicyRunPartition
 */
export interface PolicyRunPartition {
  /**
   *
   * @type {string}
   * @memberof PolicyRunPartition
   */
  policy_version_id: string;
  /**
   *
   * @type {number}
   * @memberof PolicyRunPartition
   */
  frequency: number;
}

/**
 * Check if a given object implements the PolicyRunPartition interface.
 */
export function instanceOfPolicyRunPartition(
  value: object,
): value is PolicyRunPartition {
  if (
    !("policy_version_id" in value) ||
    value["policy_version_id"] === undefined
  )
    return false;
  if (!("frequency" in value) || value["frequency"] === undefined) return false;
  return true;
}

export function PolicyRunPartitionFromJSON(json: any): PolicyRunPartition {
  return PolicyRunPartitionFromJSONTyped(json, false);
}

export function PolicyRunPartitionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PolicyRunPartition {
  if (json == null) {
    return json;
  }
  return {
    policy_version_id: json["policy_version_id"],
    frequency: json["frequency"],
  };
}

export function PolicyRunPartitionToJSON(json: any): PolicyRunPartition {
  return PolicyRunPartitionToJSONTyped(json, false);
}

export function PolicyRunPartitionToJSONTyped(
  value?: PolicyRunPartition | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    policy_version_id: value["policy_version_id"],
    frequency: value["frequency"],
  };
}
