/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetryPolicy
 */
export interface RetryPolicy {
    /**
     * 
     * @type {number}
     * @memberof RetryPolicy
     */
    max_retries: number;
    /**
     * 
     * @type {number}
     * @memberof RetryPolicy
     */
    backoff_factor?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof RetryPolicy
     */
    status_forcelist?: Array<number> | null;
}

/**
 * Check if a given object implements the RetryPolicy interface.
 */
export function instanceOfRetryPolicy(value: object): value is RetryPolicy {
    if (!('max_retries' in value) || value['max_retries'] === undefined) return false;
    return true;
}

export function RetryPolicyFromJSON(json: any): RetryPolicy {
    return RetryPolicyFromJSONTyped(json, false);
}

export function RetryPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetryPolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'max_retries': json['max_retries'],
        'backoff_factor': json['backoff_factor'] == null ? undefined : json['backoff_factor'],
        'status_forcelist': json['status_forcelist'] == null ? undefined : json['status_forcelist'],
    };
}

export function RetryPolicyToJSON(json: any): RetryPolicy {
    return RetryPolicyToJSONTyped(json, false);
}

export function RetryPolicyToJSONTyped(value?: RetryPolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_retries': value['max_retries'],
        'backoff_factor': value['backoff_factor'],
        'status_forcelist': value['status_forcelist'],
    };
}

