/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Run
 */
export interface Run {
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    run_id: string;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    policy_version_id: string;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    run_group_id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    result?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Run
     */
    run_metadata?: { [key: string]: any; } | null;
    /**
     * 
     * @type {Date}
     * @memberof Run
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof Run
     */
    last_updated_at: Date;
}

/**
 * Check if a given object implements the Run interface.
 */
export function instanceOfRun(value: object): value is Run {
    if (!('run_id' in value) || value['run_id'] === undefined) return false;
    if (!('policy_version_id' in value) || value['policy_version_id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('last_updated_at' in value) || value['last_updated_at'] === undefined) return false;
    return true;
}

export function RunFromJSON(json: any): Run {
    return RunFromJSONTyped(json, false);
}

export function RunFromJSONTyped(json: any, ignoreDiscriminator: boolean): Run {
    if (json == null) {
        return json;
    }
    return {
        
        'run_id': json['run_id'],
        'policy_version_id': json['policy_version_id'],
        'run_group_id': json['run_group_id'] == null ? undefined : json['run_group_id'],
        'status': json['status'],
        'result': json['result'] == null ? undefined : json['result'],
        'run_metadata': json['run_metadata'] == null ? undefined : json['run_metadata'],
        'created_at': (new Date(json['created_at'])),
        'last_updated_at': (new Date(json['last_updated_at'])),
    };
}

export function RunToJSON(json: any): Run {
    return RunToJSONTyped(json, false);
}

export function RunToJSONTyped(value?: Run | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['run_id'],
        'policy_version_id': value['policy_version_id'],
        'run_group_id': value['run_group_id'],
        'status': value['status'],
        'result': value['result'],
        'run_metadata': value['run_metadata'],
        'created_at': ((value['created_at']).toISOString()),
        'last_updated_at': ((value['last_updated_at']).toISOString()),
    };
}

