/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepDetails } from './StepDetails';
import {
    StepDetailsFromJSON,
    StepDetailsFromJSONTyped,
    StepDetailsToJSON,
    StepDetailsToJSONTyped,
} from './StepDetails';

/**
 * 
 * @export
 * @interface RunData
 */
export interface RunData {
    /**
     * 
     * @type {string}
     * @memberof RunData
     */
    run_id: string;
    /**
     * 
     * @type {string}
     * @memberof RunData
     */
    policy_version_id: string;
    /**
     * 
     * @type {string}
     * @memberof RunData
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof RunData
     */
    last_updated_at: Date;
    /**
     * 
     * @type {{ [key: string]: StepDetails; }}
     * @memberof RunData
     */
    steps: { [key: string]: StepDetails; };
}

/**
 * Check if a given object implements the RunData interface.
 */
export function instanceOfRunData(value: object): value is RunData {
    if (!('run_id' in value) || value['run_id'] === undefined) return false;
    if (!('policy_version_id' in value) || value['policy_version_id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('last_updated_at' in value) || value['last_updated_at'] === undefined) return false;
    if (!('steps' in value) || value['steps'] === undefined) return false;
    return true;
}

export function RunDataFromJSON(json: any): RunData {
    return RunDataFromJSONTyped(json, false);
}

export function RunDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunData {
    if (json == null) {
        return json;
    }
    return {
        
        'run_id': json['run_id'],
        'policy_version_id': json['policy_version_id'],
        'status': json['status'],
        'last_updated_at': (new Date(json['last_updated_at'])),
        'steps': (mapValues(json['steps'], StepDetailsFromJSON)),
    };
}

export function RunDataToJSON(json: any): RunData {
    return RunDataToJSONTyped(json, false);
}

export function RunDataToJSONTyped(value?: RunData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'run_id': value['run_id'],
        'policy_version_id': value['policy_version_id'],
        'status': value['status'],
        'last_updated_at': ((value['last_updated_at']).toISOString()),
        'steps': (mapValues(value['steps'], StepDetailsToJSON)),
    };
}

