/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RunTimeParam
 */
export interface RunTimeParam {
  /**
   *
   * @type {string}
   * @memberof RunTimeParam
   */
  param: string;
}

/**
 * Check if a given object implements the RunTimeParam interface.
 */
export function instanceOfRunTimeParam(value: object): value is RunTimeParam {
  if (!("param" in value) || value["param"] === undefined) return false;
  return true;
}

export function RunTimeParamFromJSON(json: any): RunTimeParam {
  return RunTimeParamFromJSONTyped(json, false);
}

export function RunTimeParamFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RunTimeParam {
  if (json == null) {
    return json;
  }
  return {
    param: json["param"],
  };
}

export function RunTimeParamToJSON(json: any): RunTimeParam {
  return RunTimeParamToJSONTyped(json, false);
}

export function RunTimeParamToJSONTyped(
  value?: RunTimeParam | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    param: value["param"],
  };
}
