/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Output } from './Output';
import {
    OutputFromJSON,
    OutputFromJSONTyped,
    OutputToJSON,
    OutputToJSONTyped,
} from './Output';
import type { StepMetadataBase } from './StepMetadataBase';
import {
    StepMetadataBaseFromJSON,
    StepMetadataBaseFromJSONTyped,
    StepMetadataBaseToJSON,
    StepMetadataBaseToJSONTyped,
} from './StepMetadataBase';

/**
 * 
 * @export
 * @interface StepDetails
 */
export interface StepDetails {
    /**
     * 
     * @type {Output}
     * @memberof StepDetails
     */
    output: Output | null;
    /**
     * 
     * @type {StepMetadataBase}
     * @memberof StepDetails
     */
    metadata: StepMetadataBase | null;
}

/**
 * Check if a given object implements the StepDetails interface.
 */
export function instanceOfStepDetails(value: object): value is StepDetails {
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function StepDetailsFromJSON(json: any): StepDetails {
    return StepDetailsFromJSONTyped(json, false);
}

export function StepDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'output': OutputFromJSON(json['output']),
        'metadata': StepMetadataBaseFromJSON(json['metadata']),
    };
}

export function StepDetailsToJSON(json: any): StepDetails {
    return StepDetailsToJSONTyped(json, false);
}

export function StepDetailsToJSONTyped(value?: StepDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'output': OutputToJSON(value['output']),
        'metadata': StepMetadataBaseToJSON(value['metadata']),
    };
}

