/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UINodePosition } from './UINodePosition';
import {
    UINodePositionFromJSON,
    UINodePositionFromJSONTyped,
    UINodePositionToJSON,
    UINodePositionToJSONTyped,
} from './UINodePosition';

/**
 * 
 * @export
 * @interface UIMetadata
 */
export interface UIMetadata {
    /**
     * 
     * @type {UINodePosition}
     * @memberof UIMetadata
     */
    position: UINodePosition;
    /**
     * 
     * @type {number}
     * @memberof UIMetadata
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof UIMetadata
     */
    height: number;
}

/**
 * Check if a given object implements the UIMetadata interface.
 */
export function instanceOfUIMetadata(value: object): value is UIMetadata {
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    return true;
}

export function UIMetadataFromJSON(json: any): UIMetadata {
    return UIMetadataFromJSONTyped(json, false);
}

export function UIMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UIMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'position': UINodePositionFromJSON(json['position']),
        'width': json['width'],
        'height': json['height'],
    };
}

export function UIMetadataToJSON(json: any): UIMetadata {
    return UIMetadataToJSONTyped(json, false);
}

export function UIMetadataToJSONTyped(value?: UIMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'position': UINodePositionToJSON(value['position']),
        'width': value['width'],
        'height': value['height'],
    };
}

