/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBase
 */
export interface UserBase {
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    user_auth_id: string;
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    name: string;
}

/**
 * Check if a given object implements the UserBase interface.
 */
export function instanceOfUserBase(value: object): value is UserBase {
    if (!('user_auth_id' in value) || value['user_auth_id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UserBaseFromJSON(json: any): UserBase {
    return UserBaseFromJSONTyped(json, false);
}

export function UserBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBase {
    if (json == null) {
        return json;
    }
    return {
        
        'user_auth_id': json['user_auth_id'],
        'email': json['email'],
        'name': json['name'],
    };
}

export function UserBaseToJSON(json: any): UserBase {
    return UserBaseToJSONTyped(json, false);
}

export function UserBaseToJSONTyped(value?: UserBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_auth_id': value['user_auth_id'],
        'email': value['email'],
        'name': value['name'],
    };
}

