/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLogDetails
 */
export interface UserLogDetails {
    /**
     * 
     * @type {string}
     * @memberof UserLogDetails
     */
    log_type?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLogDetails
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof UserLogDetails
     */
    level: string;
}

/**
 * Check if a given object implements the UserLogDetails interface.
 */
export function instanceOfUserLogDetails(value: object): value is UserLogDetails {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    return true;
}

export function UserLogDetailsFromJSON(json: any): UserLogDetails {
    return UserLogDetailsFromJSONTyped(json, false);
}

export function UserLogDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLogDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'log_type': json['log_type'] == null ? undefined : json['log_type'],
        'message': json['message'],
        'level': json['level'],
    };
}

export function UserLogDetailsToJSON(json: any): UserLogDetails {
    return UserLogDetailsToJSONTyped(json, false);
}

export function UserLogDetailsToJSONTyped(value?: UserLogDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'log_type': value['log_type'],
        'message': value['message'],
        'level': value['level'],
    };
}

