run_launcher:
  module: dagster.core.launcher
  class: DefaultRunLauncher
# run_coordinator:
#   module: dagster.core.run_coordinator
#   class: DefaultRunCoordinator
telemetry:
  enabled: false

storage:
  postgres:
    postgres_db:
      hostname: run-db
      port: 5432
      username:
        env: VULKAN_DB_USER
      password:
        env: VULKAN_DB_PASSWORD
      db_name:
        env: VULKAN_DB_DATABASE
