from enum import Enum


class VulkanEvent(Enum):
    POLICY_CREATED = "POLICY_CREATED"
    POLICY_UPDATED = "POLICY_UPDATED"
    POLICY_DELETED = "POLICY_DELETED"
    POLICY_VERSION_CREATED = "POLICY_VERSION_CREATED"
    POLICY_VERSION_UPDATED = "POLICY_VERSION_UPDATED"
    POLICY_VERSION_DELETED = "POLICY_VERSION_DELETED"
    BEAM_WORKSPACE_CREATED = "BEAM_WORKSPACE_CREATED"
    COMPONENT_CREATED = "COMPONENT_CREATED"
    COMPONENT_UPDATED = "COMPONENT_UPDATED"
    COMPONENT_DELETED = "COMPONENT_DELETED"
    COMPONENT_VERSION_CREATED = "COMPONENT_VERSION_CREATED"
    COMPONENT_VERSION_DELETED = "COMPONENT_VERSION_DELETED"
    DATA_SOURCE_CREATED = "DATA_SOURCE_CREATED"
    DATA_SOURCE_DELETED = "DATA_SOURCE_DELETED"
    POLICY_VERSION_VARIABLES_UPDATED = "POLICY_VERSION_VARIABLES_UPDATED"
    WORKFLOW_CREATED = "WORKFLOW_CREATED"
    WORKFLOW_UPDATED = "WORKFLOW_UPDATED"
    WORKFLOW_DELETED = "WORKFLOW_DELETED"
