[project]
name = "upload_svc"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
dependencies = [
    "fastapi[standard]>=0.112.1",
    "pandas>=2.2.3",
    "pyarrow>=16.1.0",
    "vulkan",
]


[tool.uv.sources]
vulkan = { path = "../vulkan" }

