name: Build and Test Steps

on:
  pull_request:
    branches: 'main'

jobs:
  python-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install uv
      run: |
        set -x
        pip install uv
        uv sync
        
    - name: Run tests with uv
      run: |
        uv run pytest -m "not integration"

    
  js-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-directory: ['frontend']
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies with uv
      run: |
        set -x 
        pip install uv
        uv sync

    - name: Render OpenAPI Specification
      run: |
        uv run python scripts/export-openapi.py --out ./generated/openapi.json

    - name: Generate new client
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/local" \
          openapitools/openapi-generator-cli generate \
          -i /local/generated/openapi.json \
          -g typescript-fetch \
          --additional-properties=modelPropertyNaming=original \
          -o /local/generated/ts

    - name: Copy generated files
      run: |
        set -x
        mkdir -p ${{ github.workspace }}/frontend/generated/
        cp -r ${{ github.workspace }}/generated/ts/* ${{ github.workspace }}/frontend/generated/
        ls -la ${{ github.workspace }}/frontend/generated/

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: '${{ matrix.node-directory }}/package-lock.json'
        
    - name: Install dependencies
      working-directory: ${{ matrix.node-directory }}
      run: npm ci
            
    - name: Build
      working-directory: ${{ matrix.node-directory }}
      run: npm run build

