name: Build Speakeasy SDKs

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
      runs-on:
        description: Runner to use for the workflow (e.g., large-ubuntu-runner)
        type: string
        default: ubuntu-latest
  push:
    branches: ["refactor-ci-pipeline"]


jobs:
  build-openapi-spec:
    runs-on: ubuntu-latest
    outputs:
      spec: ${{ steps.archive-generated-files.outputs.spec }}
    steps:
      # Generate OpenAPI Specification
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies with uv
        run: |
          set -x 
          pip install 'uv<0.8'
          uv sync

      - name: Render OpenAPI Specification
        run: |
          uv run python scripts/export-openapi.py --out ./generated/openapi.json

      - name: Archive generated files
        id: archive-generated-files
        uses: actions/upload-artifact@v4
        with:
          name: spec
          path: generated/openapi.json
          if-no-files-found: error

  build-ts-client:
    runs-on: ubuntu-latest
    needs: build-openapi-spec
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install root dependencies
        run: |
          cd frontend
          npm ci

      - name: Generate new client
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/local" \
            openapitools/openapi-generator-cli generate \
            -i ${{ needs.build-openapi-spec.outputs.spec }} \
            -g typescript-fetch \
            --additional-properties=modelPropertyNaming=original \
            -o /local/generated/ts

      - name: Archive generated files
        uses: actions/upload-artifact@v4
        with:
          name: ts-client
          path: generated/ts
          if-no-files-found: error

  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr
      set_version: ${{ github.event.inputs.set_version }}
      speakeasy_version: latest
      github_repository: vulkanlabs/vulkan-client
      runs-on: ${{ github.event.inputs.runs-on }}
    secrets:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}