name: Build Speakeasy SDKs

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
      runs-on:
        description: Runner to use for the workflow (e.g., large-ubuntu-runner)
        type: string
        default: ubuntu-latest


jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr
      set_version: ${{ github.event.inputs.set_version }}
      speakeasy_version: latest
      github_repository: vulkanlabs/vulkan-client
      runs-on: ${{ github.event.inputs.runs-on }}
    secrets:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}