name: Publish Packages to GitHub Packages

on:
  push:
    branches: [main]
    paths:
      - 'frontend/packages/**'
      - '.github/workflows/publish-packages.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Install root dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Build all packages
        run: |
          cd frontend
          npm run build
          
      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd frontend/packages
          
          # Function to publish a package
          publish_package() {
            local package=$1
            echo "Publishing @vulkan/$package..."
            cd $package
            
            # Check if package version already exists
            PACKAGE_NAME=$(node -p "require('./package.json').name")
            PACKAGE_VERSION=$(node -p "require('./package.json').version")
            
            if npm view "$PACKAGE_NAME@$PACKAGE_VERSION" > /dev/null 2>&1; then
              echo "Package $PACKAGE_NAME@$PACKAGE_VERSION already exists, skipping..."
            else
              npm publish
              echo "Published $PACKAGE_NAME@$PACKAGE_VERSION"
            fi
            
            cd ..
          }
          
          # Publish packages
          for package in base api-utils client-open; do
            publish_package $package
          done