name: Build Python Packages

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version to use'
        required: false
        default: '3.12'
        type: string

jobs:
    python-build-packages:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
        
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: ${{ inputs.python_version }}
        
          - name: Install dependencies with uv
            run: |
                set -x 
                pip install 'uv<0.8'
                uv sync
        
          - name: Build Python Packages
            run: |
                uv build --wheel --all