name: Test Steps

on:
  pull_request:
    branches: 
      - "*"

jobs:
  python-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install uv
      run: |
        set -x
        pip install 'uv<0.8'
        uv sync
        
    - name: Run tests with uv
      run: |
        uv run pytest -m "not integration"